### ISSUE TITLE
UX: Mobile - Topic attachments are not in a convenient place

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#103]
**Reproduce**

* Open `/topics/:topicId` in your mobile device or a narrow screen

**Result**

* Cannot find the "Attachments" section as they are hidden away in the "Settings"

**TODO**

- [x] Talk to UX people, find a more visible place for the "Attachments" on small screens.
- [x] Implement the proposed solution

![image](https://user-images.githubusercontent.com/7405383/47803823-01a27380-dd3c-11e8-8147-8d11d4bc9639.png)

**Comment by ilmartyrk** [comment]
@kevincrepin what do you think? I could only think of adding a button/link next to topic info that would reveal attachments or open settings section where the current attachments are
![opinion](https://user-images.githubusercontent.com/19904307/50705326-216b5600-1063-11e9-9e15-c79c9add3679.PNG)

**Comment by ilmartyrk** [comment]
@kevincrepin, have you had any time to think about it?

**Comment by kevincrepin** [comment]
Sorry, will put it on my TODO!

**Comment by kevincrepin** [comment]
So kinda thinking that these 3 dots are very unclear as well, so took that on with this update as well. The function is still the same, the details are closed on default, but we have a label and an indication if there are attachments also there. And then the attachments are visible in these topic details.

BTW also added the reporting as it was missing from mobile view. But what do you think of this? I think this is still a rather short-term/quick solution to the current problem. I think the top menu needs to be revised because the options / settings icon is also not really clear and maybe the details in general don't open up inline, but in a popup where you can edit ... Food for a bit more thought.
![screenshot 2019-01-14 at 17 32 51](https://user-images.githubusercontent.com/26792281/51122634-f16e4080-1822-11e9-8f16-fb5b8b040fa0.png)

**Comment by ilmartyrk** [comment]
Thank you @kevincrepin, looks really good. Can you please add this to invision with assets.

**Comment by kevincrepin** [comment]
https://projects.invisionapp.com/d/main#/console/9829159/341199441/preview + https://projects.invisionapp.com/d/main#/console/9829159/341199442/preview

Asset: https://projects.invisionapp.com/d/main#/console/9829159/241763981/inspect and also attached here to make it easier
[Archive.zip](https://github.com/citizenos/citizenos-fe/files/2763581/Archive.zip)

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-fe/commit/26c8caec958c859e13537389b81de2f07275c298
