### ISSUE TITLE
Inviting users with "none" rights 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1066]
While trying to work out the point of "none" rights for the HC texts, I found a lot of weird things happen when inviting myself (with a different account) with "none" rights. 

Like for example the topic not being created (i.e. not appearing in the "my topics" of the account I created it with), the topic name in the email showing as a really long URL instead, and getting an error saying "sorry the invite has been deleted" when trying to join it with none rights one time, but getting a "you don't have sufficient permission to access" another time. 

But maybe I'll leave this to @ssin1901 to test out more if that's OK? But just wanted to flag that there are issues. 

Though again probably something that doesn't happen much in real life as I can't think of a situation in which someone would be invited with "none" rights, as it means they can't access it. 

So am wondering what is the point of having the option available to invite someone with "none" rights, and therefore it could just be removed from the options in the invite feature? 

@ilmartyrk @anettlinno @ssin1901

**Comment by anettlinno** [comment]
You are right, Becca, this needs a proper user story as the current one is not valid (the one where User wants to invite a topic into the group and give access to the topic only for certain people. But this user story doesn´t work as if User is adding the topic into the group, then one can give and change topic rights for all the group members and not for individuals. Once the topic is in the group, only then can Admin User change individual rights but then it´s already too late).

**Comment by BeccaMelhuish** [comment]
Aha OK I see the idea behind it now! Though just to add that in that use case you just described it seems that with the current set up the users with "none" rights would still get an invite saying: "X is inviting you to X". But when they click on the link they'll not be able to access it (as they are invited with "none" rights) which would be quite confusing and annoying.. (Though this may be what you just said actually, I didn't follow it fully :D)

**Comment by anettlinno** [comment]
@BeccaMelhuish that was what I was trying to say, yes :)

@loorm @ilmartyrk do you remember what was the user story for the current "none" user rights -- in which situation can User use it on our current platform version? Because every use case that I can think of, does not serve its purpose. Here are two main:

1.  _User story where Admin user adds topic into the group and wants to give some users "none" rights, so that they couln´t see the topic in the group._ Admin user cannot change individual users rights BEFORE adding topic into the group. One can only do it after the topic is already added into the group and all users have received notifications. To me this is the most logical reason for using "none" rights, but it doesn´t serve its purpose as Admin User cannot change individual rights :) 
2. _User story where User invites local community members into the topic but in topic creation phase wants to give editing rights only for some people. To other people Admin user will give "none" rights, so that they wouldn´t see the topic OR receive an invitation yet._ Admin User can invite all the community members once and give "none" rights for some users (and later change their rights is needed), but this doesn´t make any sense as Admin User would still need to do extra moves later (changing User´s rights). To me it´s the same if to invite certain people later into the discussion (after topic is created for example)... **AND I tested that when inviting people with "none" rights they still receive an invitation**, but cannot access to topic.

Your help is needed please :)  

IMHO, if we cannot find any working user case, then we should remove the "none" rights from the options.

**Comment by BeccaMelhuish** [comment]
@anettlinno when writing the (currently still just draft) HC text about user rights, this is what I came up with as a reason why "none" rights might be useful. But this is only useful once the user has only joined, there would still be no point (to my mind) in having "none" as an option when inviting a user.. 

![image](https://user-images.githubusercontent.com/61320526/181003826-586077df-56cc-4a79-ad8a-bfc5aa35c9ab.png)

**Comment by anettlinno** [comment]
> @anettlinno when writing the (currently still just draft) HC text about user rights, this is what I came up with as a reason why "none" rights might be useful. But this is only useful once the user has only joined, there would still be no point (to my mind) in having "none" as an option when inviting a user..
> 
> ![image](https://user-images.githubusercontent.com/61320526/181003826-586077df-56cc-4a79-ad8a-bfc5aa35c9ab.png)

OK, thanks for sharing! Yes, it might make sense if someone wants to suspend a User´s access in existing topic (and maybe not from all topics in a group?) but it is still rather edge case, I would say :D 
AND then the "none" rights are not very useful under  the "Inviting a user" rights options as you said...

**Comment by anettlinno** [comment]
Triage 70. Moving this discussion under #1068 and closing this issue.
