### ISSUE TITLE
Remind people to vote

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#111]
**Overview**

Add a possibility to send out reminders to Topic members about the vote to increase vote participation.

**TODO**

- [ ] FE: Figure out the UX of the feature
- [ ] API: Create the required API routes to implement the feature. Add tasks to https://github.com/citizenos/citizenos-api

**Comment by BeccaMelhuish** [comment]
Mikk mentioned this GitHub issue when we discussed the FAQ: "Can I see who has voted while the vote is still in progress?", which we've not yet found a way to solve yet (other than using an FAQ/help icon to tell them that they can't and why they can't, which isn't really a full solution). 
 
The issue this would help solve being that vote admins want to be able to see who has voted, so that they can shimmy along those who haven't yet, and are disappointed that they're not able to do this.  

This seems a great solution to me - to have a way for the admin to send a message to all those who have not yet voted. And ideally they could include a personalised message e.g. "You've received a new message from (Admin Name)" email subject, with a space for the their message in the body of the email. Rather than it just being an automatic reminder. 

What do you think @anettlinno @loorm @ilmartyrk @kevincrepin?

**Comment by BeccaMelhuish** [comment]
Also, are there any other situations in which/reasons why it would be useful for an admin to message members of a topic or group through the system, rather than just through their own channels? 

If so, perhaps this could be a bigger enhancement - a messaging feature. In which admins can choose from a drop down box, whether they message all members, those who have voted, those who haven't voted, any other categories I haven't thought of.

**Comment by BeccaMelhuish** [comment]
And this is going beyond the scope of the FAQ now, but seems sensible to consider it in connection with this so will include it here anyway. (Let me know if better to move it to a separate issue though?).  

Thinking bigger, this would then open up the possibility for users to receive messages from us into a messages inbox within the platform.  So that we could update them on new features, or any other important messages we want to get through to them. 

It's often occurred to me that we have no direct way of contacting our users (only hoping that they follow our social media channels, but I'm sure most do not), which would be very valuable for Marketing purposes (if done carefully to avoid "spamming" them) as well as product development (i.e. if we want to recruit willing and diverse participants for user research/testing, especially thinking about the next version of the platform) and for user experience (to ensure they have all the info they need to use the platform effectively and happily (e,g, when we wanted to reassure users about Security, so put out a blog about it; or when we launch our new Help Centre; or when we're getting another question being frequently asked, and want to communicate the answer to all users). 

Of course, as we presumably have all our users email addresses from their registration, it would also be feasible to email them directly using those. I assume that's something that's been discussed in the past and decided against though? And presumably also some GDPR issues, but none that couldn't be got around (i.e. a one-off pop-up asking for permission). 

Another option to consider would be using notifications for this purpose, perhaps incorporating them into the Activity feed, but making it more prominent so that users can't miss them (like the social media red dot). Or one-off pop-ups could also work, but perhaps a little annoying for users.    

@liinaguiter will tag you here too as is partly Marketing related :)

**Comment by ilmartyrk** [comment]
Closing this as it probably should be solved using notification system. https://github.com/citizenos/citizenos-fe/issues/718
