### ISSUE TITLE
Group rights in public group

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#1129]
**What is the problem?**
As a User, when creating a public group and adding new existing topic in group then I can set topic rights:

<img width="331" alt="Admin group rights" src="https://user-images.githubusercontent.com/45175679/206431073-114b13b5-a5f0-4d18-990a-5ebf9c6e2dde.png">

As a User who joins public group, I get notified that I´m being added with reading rights only:
<img width="332" alt="Group rights in public group" src="https://user-images.githubusercontent.com/45175679/206431255-44779ff3-b235-4aa7-9102-f3b1f23e5e6b.png">

**Why is this a problem?**
Currently there´s a contradiction and if I remember correctly then we agreed that public topic participants have only reading rights. BUT they can ask to change their role from Admin users. 

**Possible solution.**
Please remove option to choose topic rights when adding it to a public group.

**Comment by anettlinno** [comment]
@ilmartyrk when creating a new topic in the public group then Admin user can still set topic rights (see on the first picture above), so that everyone in the group have the same rights (admin, edit or participant). I think we should not allow setting topic rights when a new topic is created within a group. 

Two thoughts how to solve it:
1. IF we allow creating a new topic within a group, we should add an explanatory text (same text to what you added when finding and adding a topic in the group): "group **members** rights over topic: participant"
2. We do not allow creating new topics within the public group. The flow would be that Users have to create topic under the "Create topic" and under the Groups actions, they can add topics into group.

**Comment by ilmartyrk** [comment]
@anettlinno removed creating of a new topic from settings, initially thought that hiding the dropdown would work, but as creating a new topic will redirect away from group settings flow it didn't make sense to keep it there. Still user can search and add existing topics. Also while creating a group as private, user can change topic permissions, then when he/she changes group visibility topic permissions stay as they are. But actually I added a fix so that if visibility is public topic permissions will be read.
