### ISSUE TITLE
BUG: partner logo eats into text

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#152]
Currently, partner's logo may hide the descriptive text in the topic box (pls see the screenshot below). Should be resolved in a way so that it never interferes with the text, regardless of the image selected by the partner.

![screenshot 2019-01-07 at 11 55 54](https://user-images.githubusercontent.com/34126353/50768995-30cce800-128b-11e9-98af-1e9a57a7faa4.png)

**Comment by tiblu** [comment]
Fixed by adjusting general styles for LDI logo.

@kevincrepin
It would help, if all the icons would be based on same design principles, mainly being as full circles like the Let's Do It Indonesia. Right now all the icons are different in shape, having top cut off or both. This does not allow us to scale the background to give more space for the text.
Also from development point of view it is always a headache where you have to do exceptions per new icon.
BUT, we do not have to go revamping all the icons right now, IF we have a new one coming along, I would then update all the icons to a standard format - full circle.

![image](https://user-images.githubusercontent.com/7405383/67671415-94411700-f97e-11e9-9c5a-16192a9d0d9a.png)

**Comment by loorm** [comment]
Fix confirmed. Tried resizing the window to various sizes. Logo always stayed clear of text.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
