### ISSUE TITLE
FEATURE: Pin topics on home page

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#155]
There is a request for possibility to pin important topics to home page. There are cases when some important topics might get pushed out of sight on clients page and so there should be an options where "superadmin" could possibly pin important topics to always be first in the public list.

**Comment by tiblu** [comment]
**The need**

It is evident, that some organizations want to rise the visibility of selected Topics on the Home (front) page of the application by pulling them to the top of the list.

**I propose the following solution**

* Any Moderator can pin/unpin Topics to Home page.
* Warn moderator that pin/unpin is a public action - Moderators name will be publicly shown. @kevincrepin
* Pinned Topics are pulled to the top of Home page, ordered `updatedAt DESC` (same as others), rest of the Topics follow the pinned ones, NO DUPLICATES.
* There needs to be an indicator that shows a Topic being pinned AND some kind of text/tooltip which moderator pinned the Topic - "pinned by Mikk (moderator)".  @kevincrepin 
    * Why the public name of the moderator? - It gives more visibility over what is prioritized and by whom. This  to guarantee accountability and visibility over Moderator actions.
* IF any of the filters is applied, the pinning still counts. That is, if I choose a category, topics that have the category AND are pinned are still on top of the other category results.

@ilmartyrk @kevincrepin Do you see any issues with this approach? And we need @kevincrepin help on the UX.

**Comment by ilmartyrk** [comment]
Only problem part for me is how to store these topics. Seems that this needs separate table with topicId, partnerId and pinnerId (moderatorId)? Else everything seems reasonable and clear

**Comment by kevincrepin** [comment]
I think this pinning is...maybe a bit of a problem given the current design. Pinning topics works in formats like a forum, but even there you can't start pinning tens of topics, because the point gets lost then. 

Since our topics take up so much visual space already AND we have brand/client topics which are already pinned to the top by default, we basically allow for a home screen which becomes very static – and it should be the opposite ideally.

This is actually something that needs a bit more thought from UX pov, because a quick solution here wouldn't really work. For example, splitting up the pinned and regular (latest posts) in categories would still present the issue of having a non-dynamic home screen...

Might be time to reconsider how topic are visualised: grid vs list...

**Comment by ilmartyrk** [comment]
Closing as we have this feature
