### ISSUE TITLE
FEATURE: inconsistent use of delete term / function

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#192]
**Problem:** when "deleting" arguments or replies, they are never actually deleted. An overlay is applied, which says the argument is deleted, but it can still be viewed. Whereas a topic can be deleted without a trace.

**Why is this a problem?** First of all, because it is inconsistent. A user does not know, what to expect, when hitting the "delete" link. Will the content be deleted deleted or merely hidden? Secondly, allowing whole topics to be deleted creates significant room for censorsip. Closing topics is fine. Possibly archiving them, too, so they don't show up at all in My Topics view any more. But completely deleting a topic goes against the beliefs and values of Citizen OS.

**Possible solution:** unify "delete" function across the platform to always mean hiding and / or archiving. Make this clear to the user via dialogs, when they are "deleting" content. Only allow deleting deleting for admins / moderators in case of serious code of conduct violations.

Also, check dialog messages. The dialog for deleting an argument right now implies, that it will be completely gone. It should, instead, make reference to the fact, that it will be hidden, but will continue to exist.

**Comment by ilmartyrk** [comment]
Still relevant. Argument deleting dialog should probably include the description of actual result of this "deleting". Archiving will probably need some behaviour changes in our API logic.

**Comment by anettlinno** [comment]
The current logic and flow of deleting an argument is following (just thinking out loud): 

1. User deletes the argument without being acknowledged that the argument will not be permanently deleted (and hidden) and will be seen for everyone. 
<img width="741" alt="Delete" src="https://user-images.githubusercontent.com/45175679/144011702-76c04ead-1b2f-442a-bfc9-e10b1f890834.png">

2. After deleting the argument, our system is saying that "This argument was found inappropriate by user" and leads to "Codes of Conduct" where is the topic moderation information. BUT this topic was deleted by the user herself, not by the moderators. In my mind it´s not quite correct because as a user, I decided to change my mind when wanting to delete this argument and it wasn´t reported by any other user or moderator. 
<img width="514" alt="Delete2" src="https://user-images.githubusercontent.com/45175679/144013109-6b93042b-27bf-4080-8a02-8206e03fc4b2.png">

3. When user clicks on "View argument anyway" she sees argument twice -- 1) in the argument area 2) in the red box. Text "This argument was deleted by user" is disappeared. 
<img width="400" alt="Delete3" src="https://user-images.githubusercontent.com/45175679/144014493-38561ca0-24d5-41d9-acb5-948e3e5da0cb.png">

Some ideas to make this flow more user friendly :) 

- When clicking on the "Delete" option, then we should make it clearer with the dialog (as suggested by Margo) that her argument will not be permanently deleted and everyone can still view it
- When user deletes the argument herself (and it is not reported) we should say that it was deleted by the user (and we shouldn´t provide reason, as we don´t know for what reason). IF we still want to keep the "Why" then we could add one point into the "Code of Conduct" with the explanation that user herself can delete her arguments any time but that these will not be deleted permanently. 
- Deleted arguments UX could be more clear but I don´t have nay good solution to provide there currently.

**Comment by anettlinno** [comment]
Triage 53. We should change the terminology and find new word to replace "Delete" with more accurate one. 
One idea that we discussed is that after user deletes the topic it could be archived for some time period (6 months or 1 year) and after that deleted permanently. 
Sending this issue back to In Prep for further discussion.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/59
