### ISSUE TITLE
UX: leaving edit mode is unclear

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#227]
**What is the problem?**
When user is in edit mode it's currently not clear how to go out of edit mode. 

**Why is this a problem?**
Confusing. First, because there's no obvious way for leaving the edit mode. Second, because UX is inconsistent in web app, where sometimes you need to press a button to save your work (like settings), while in edit mode you don't. So you don't dare to simply leave and there's no button to click for saving and leaving edit mode.

**Possible solution**
We need a "leave edit mode" or a big blue "save changes" button or whichever is clearest, but we need something. 

<img width="1206" alt="Screen_Shot_2018-06-04_at_13 55 08" src="https://user-images.githubusercontent.com/22661743/55436419-e6ff4f80-55a4-11e9-885a-df45381beae1.png">

**Comment by kevincrepin** [comment]
The screenshot attached comes from the design, so I actually can't add more to it. Basically we just need this blue button :)

**Comment by loorm** [comment]
Instead of "Save changes" the button should say "Done editing". Otherwise users will think that they can make changes in the topic without saving, which is not correct (Etherpad autosaves constantly).

**Comment by tiblu** [comment]
@loorm Done!

Notes on the implementation:

* Affects only desktop view as mobile view already had an edit toggle at the top.
* @loorm We MAY want to make the button always visible, it would toggle edit mode on/off. Right now it is a weird experience where exiting edit mode is from a button, but entering is from a link in the Settings menu.
* Screenshot below shows an edge case where 2 buttons - "Done editing" and "Send for review" are visible at once. This case only happens when you are editing a moderated Topic. Adding it here in case we want to separate them better.

![image](https://user-images.githubusercontent.com/7405383/64161004-8f139000-ce45-11e9-8333-a025edafa48d.png)

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
