### ISSUE TITLE
add labels to topics, get rid of categories

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#238]
**What is the problem?**
Categories are stiff, hard-coded and adding new ones takes time. Not an ideal option for categorising and filtering topics. Right now, they're only useful for public topics.

**Why is this a problem?**
As the number of topics increases, an efficient way for sorting and filtering, including for private topics, becomes necessary. Categories is a suboptimal solution.

**Possible solution**
Add tags/labels to topics. Make them useful regardless of public/private status. Make them freely user-creatable. Add searching / sorting / filtering options based on tags / labels.

**Comment by loorm** [comment]
@kevincrepin Do we have any views for this? If not, could you please come up with some?

**Comment by kevincrepin** [comment]
@loorm @tiblu I think with this we need following changes:

- search will also show topics according to tags, which means tags need to be visible in the search. Otherwise it's not clear why they show up.

- adding categories in topic settings needs to change to adding tags. They get added via a free inputfield which has an autocomplete so there's some hope in unifying tags a bit.

- My topics. Should the list view show tags? Or shall we only show tags in the "General information? Or even only in the opened topic? If we allow sorting/finding via tags in my topics, they need to be visible at this level as well, I think.

- Issue: The search results overlap the list view + detail. So it's currently not a great experience to use it as a filter. In fact it's impossible, we only have our dropdown currently for ordering etc. But we can't use a dropdown for tags, since we have no control over how many there are.

So I think because of this last issue our entire search logic also needs some looking at. On those screens where it would be used to narrow down a list, it doesn't make much sense to overlap the list view... Let's say I have 5 topics about "Ecology", using the search I can find them,  but what happens if I open a topic? The page refreshes and opens that topic. But I have lost my "filtered down" view.

Just wanted to bring this up here for more comments from you guys. I think this needs a bit proper rethinking, considering it does change some behaviours in different places.

**Comment by loorm** [comment]
Valid points. Perhaps we need both:
- categories as shared, public sorting criteria
- tags as personal, user-specific (as in everyone has their own tags) sorting criteria

Need to create a better user story for this.

**Comment by loorm** [comment]
@kevincrepin had a valid point above about how the way we currently display search results, is suboptimal. I agree, but I would not like to continue on this point here, in order to keep one Github issue about one feature. Let's keep this one about labels.

Categories seem to serve a purpose for public topics, so let's exclude that from this issue too. Categories will remain as they are.

Now, the **user story** is, that as a user who has been using the system even for a little while, the list of My Topics becomes quite long and somewhat cluttered. As that user, I would like some way to better group and sort my topics. Something akin to labels in Gmail, but not so sophisticated (they have label nesting etc). I would like those labels to be just for me, privately. And I would like to be able to customize their appearance to some extent (choosing a color, an icon, editing the name).

Currently, I do have some sorting options. I can group topics into groups. I can pin some of them. I can sort them according their status in My Topics view. But I currently have 203 topics and the present grouping and sorting options are somewhat limited. So the main sorting feature I need is somehow (either through search or someelsehow) to only see topics in my list that have a certain label. Very similar to "Show all my pinned topics", except this would be "Show all my topics with label X". Answering another of Kevin's questions, the labels are most useful in My Topics view, so they should be visible there. In the list, not in the General Information. Maybe changing lables works through the General Information somehow. And there's very little need to see labels in opened topic. 

Anyway, @anettlinno has heard this need from clients, too. I think clients proposed to have folders, but labels / folders / tags all sort of server the same purpose. I hope I've done enough to clarify the need, so that @kevincrepin, @ilmartyrk and @anettlinno can now take over and work out, what the labels are actually going to look like.

**Comment by kevincrepin** [comment]
We gave this a thought and worked out a version with folders, how to add and manage them: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1060%3A29260

**Comment by loorm** [comment]
UX - are users going to be able to tell the difference between folders and groups?

That's why I would prefer labels. Also, because a single topic can have multiple labels, but folder logic is usually, that something can be in one folder at a time.

But more opinions are needed here @anettlinno

**Comment by anettlinno** [comment]
This is well known issue for users with more than 20 topics under My topics :)  

Sorting public topics with categories works well in my mind and I would also leave it as it currently is. Project categories like Biotoopia, 34 Island Project etc are confusing and probably should be displayed in the end of drop-down menu not in the beginning. 

For grouping and sorting My topics I would also prefer labels instead of folders and leave the folder system for My groups to keep it simple. 

I don´t have any good solution to provide for the labels or tags system but what I really like is how Trello has solved this problem:

![Labels](https://user-images.githubusercontent.com/45175679/136208989-19c01ce1-b11e-4377-8695-4334b8253ee6.png)

As a user I have an opportunity to differentiate cards by colors and also name those accordingly. In our platform we could provide similar kind of opportunity to label topics and sort these according to the colors (and names?). User could harvest these under the drop-down menu: 

![Dropdown](https://user-images.githubusercontent.com/45175679/136210243-394b9fdc-99aa-4724-a667-8d0b468ce698.png)

This raises some questions:
- How to make users understand that categories are helpful and important only for the public topics and that labels are only for their private use? I´m thinking that if categories would stay under the "Settings" and labeling is taking place under "My topics", would that make it clear that labels are only for private use?
- How to make users understand where they can sort topics by labels? Would it be possible to display all green labeled topics if user clicks on green tag so that they wouldn't have to know and find the drop-down menu?

**Comment by kevincrepin** [comment]
Tagging @tiinadux here as well

**Comment by anettlinno** [comment]
Update: labels and categories grouping system has been included into the redesign project.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/50
