### ISSUE TITLE
difficult to find user management options

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#239]
**What is the problem?**
When in topic editing / viewing mode, it's difficult for user to find user management. Inviting users is available in the right hand menu, but changing rights, removing them is hidden away in My Topics view. Need to navigate out of view / edit mode and back to My Topics to find this.

**Why is this a problem?**
Complicated, confusing for the user. There have been users, who are completely unaware of the user management screen in My Topics, they thought inviting users is the only option in Citizen OS. Even if you know where it is, it's cumbersome to move between different view to manage settings relevant to the same topic.

**Possible solution**
Possibly move user management to settings dialog.

**Comment by kevincrepin** [comment]
For now the easiest is indeed moving it to the settings dialog, but a couple of changes need to happen which I will outline below:

In the sidebar options The settings and invite users lead to different dialog windows.
Settings holds general settings, categories (in the future tags), users and groups: https://projects.invisionapp.com/d/main#/console/17224475/362196833/preview

Inviting opens up a different dialog window which also includes the sharing: https://projects.invisionapp.com/d/main#/console/17224475/362196832/preview

By dividing this we also don't have the situation anymore that read users can open the general settings dialog window.

**Comment by loorm** [comment]
Triage 42. @kevincrepin In "My Topics" view, we currently have the accordions for "Activity feed", "Group list" and "User list". 

In order to make user managerment easier to find, we would like to have the same logic in "Invite users" dialog window. Except here the accordions would be for "Group list", "User list" and "New invitations".

What do you think? Maybe you have a better idea, how to bring user management into "Invite users" dialog?

**Comment by kevincrepin** [comment]
I wouldn't add it to invite users dialog actually. It would become too messy trying to add all of this into a place with already a lot going on.

I would then rather suggest having it as a separate dialog "manage users" or "manage users & groups" or something in this line. Then we can have different tabs for users, groups and invited, instead of trying to fit it all into one tab under "invite users".

Example: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=440%3A20359

But these dialog windows are getting quite complex with this + invite/share task etc. Actually not ideal for these types of content which can be long lists to confine it into a dialog window. 

I know I'm repeating myself :) But I think all the topic management flows should be reconsidered and redesigned with most of these flows not confined within the dialog windows.

**Comment by loorm** [comment]
We have views. The functionality is identical (and would ideally peruse the same code) as the user management functions in "My Topics" view. We add a menu item to the "Actions" menu on the right of the topic called "Manage users". Then proceed according to Kevin's views. 

Moving to Triage.

**Comment by anettlinno** [comment]
Triage 45. Discussed and will send it back to in preparation list. @anettlinno

**Comment by ilmartyrk** [comment]
Development tasks:
- [ ] Should include https://github.com/citizenos/citizenos-fe/issues/670
- [ ] Create new view
- [ ] Alter API requests

Administrative tasks:

- [ ] Update CHANGELOG files
- [ ] Inform marketing of new feature(s)
- [ ] Inform localization on new translations

**Comment by anettlinno** [comment]
Triage 47. High priority development. Est. dev. time. 4 days. Sending to development together with #670.

**Comment by anettlinno** [comment]
@kevincrepin we would like to ask you a little design update here: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=440%3A21327 

Please add user emails in User list design (this can be developed together with issue #670) 

In current design me as a user don´t understand who are the "invited" ones? I understand that when I click on "Manage users" and land on the users list then these are people who are invited into this topic. The next tab "Groups" I understand that these are my groups and I can change group rights from there. But "Invited" -- who are they? Are they people who are invited (and pending) to this topic that is open or they are invited (and pending) to any certain group? Thank you in advance!

**Comment by kevincrepin** [comment]
Added the user e-mails

Invited users are invited to the topic, not the group. It's done at topic level. Why did you think it was to a certain group? Is it confusing because of the groups tab also included in this popup?

Also thinking that maybe "users" is a bit of an artificial term which doesn't apply very well here. What about "participants"?  It would have to change everywhere then, just not use "users" as a term at all anymore?

https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=440%3A20359

**Comment by anettlinno** [comment]
> Added the user e-mails
> 
> Invited users are invited to the topic, not the group. It's done at topic level. Why did you think it was to a certain group? Is it confusing because of the groups tab also included in this popup?
> 
> Also thinking that maybe "users" is a bit of an artificial term which doesn't apply very well here. What about "participants"? It would have to change everywhere then, just not use "users" as a term at all anymore?
> 
> https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=440%3A20359

Yes @kevincrepin I think that invited tab is confusing because of the groups tab which is in the same window. 

I like the idea of changing "users" to "participants". When we are talking about discussions then we are talking about participants -- people who are actively taking part of (online) conversation. Participants are contributing into the (two-way) communication. Users are more passive -- like consumers.

This decision needs @BeccaMelhuish and @seppviljar input too. Becca, could you please comment it from the native speaker´s perspective. And Sepp, how would it affect the translations? Are there any languages where the "participants" would be like the Hvannadalshnjúkur mountain in Iceland? :)

**Comment by seppviljar** [comment]
Yeah, the good old "user" - in Skype we tried to avoid it too, where it made sense.

My few cents:

  *   I'm all in for changing it where it actually denotes a... well...  a participant - like discussion, voting etc
  *   I'd maybe keep "user" where the connection is vague or generic, a la activity feed "User Sepp created profile"
     *   ie small differences where you are platofrm user vs discussion participant
  *   There are approx 170 strings mentioning "user", 2/3 from Activity feed, roughly - so not exactly cheap to change everything
  *   The length is mostly fine - https://translated-into.com/participant 🙂

**Comment by anettlinno** [comment]
Triage 48. User list under the general information will follow the same logic as Kevin provided in the user management pop-up window design. Extra tab for people who are invited (but whose invitation is pending) will be created. Est. dev. time 3 days.

PS! Only admin user sees emails. Other users sees only participants list (without emails).

I will open new issue to discuss the user vs participant topic.

**Comment by KatiVellak** [comment]
As discussed, only admin users can see emails, other only see the list of participants. @ilmartyrk can make relevant restrictions.

**Comment by ilmartyrk** [comment]
Is now live, related to this issue, updated API to order results, as pagination and sorting in my topics view didn't make sense anymore in the way it was initially done when we loaded all results from API

**Comment by anettlinno** [comment]
How great! :)) Tested and works beautifully!
