### ISSUE TITLE
FEATURE: add deadline for topic discussion (in progress) phase

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#242]
**What is the problem?**
If a user wants to have a discussion for a week and then move on to voting, then they have to open a topic to start the discussion, then make a separate calendar entry to their off-site calendar to move the topic into voting on a specific date. On that date navigate back into Citizen OS to change topic status. 

**Why is this a problem?**
It makes the process longer and more complicated for the user than it has to be. Also, the author / admin can be busy in a meeting somewhere, with users anxiously waiting to start voting on the agreed date. This creates frustration, bottlenecks.

**Possible solution**
Make a similar deadline for discussion phase as there already is for the voting stage. On that deadline the topic automatically changes status without the author / admin having to do anything.

**Comment by ilmartyrk** [comment]
This is interesting task. It probably should be solved under create voting and setting a pre-defined vote start date as the vote setup should be done before changing the status.

**Comment by anettlinno** [comment]
Triage 55. There are different options how to solve this issue and needs user story. 

Sending back to in prep.

**Comment by loorm** [comment]
> This is interesting task. It probably should be solved under create voting and setting a pre-defined vote start date as the vote setup should be done before changing the status.

Yep, voting system setup page makes sense as a location.

**Comment by loorm** [comment]
> Triage 55. There are different options how to solve this issue and needs user story.

The feature request was intended to be the user story, describing what the user needs and why.

**Comment by anettlinno** [comment]
If I understand correctly, then there are two needs for this enhancement:
1. To promote debating and discussion before the final decision-making;
2. To improve user experience in planning the discussion and decision-making. 

It would help people to make better, more informative decisions by reading all the pros and cons that are left in this topic (perfect world example :)) ). Currently our platform works so that argumentation part is open throughout the whole decision-making process (incl. voting) and people discuss and vote at the same time. I agree that separating debating/discussion from voting makes the five-step decision-making process more clear (idea gathering, co-creation, discussion, voting, follow-up). 

Setting the deadlines for discussion and voting can take place only after idea gathering and/or document co-creation process and doing it on voting system setup page is most reasonable, as suggested above.

There are few aspects we need to think through:

- If our system automatically closes discussion part and sends topic to voting, then admin user(s) should be notified before that, because if there are any changes needed to be done inside the text (important updates that came out during the discussion), they should be able to do those;
- If admin user wants to change deadline of discussion or voting, then this should be also easily doable (under settings?);
- If our system automatically sends document to voting then should the discussion part be closed?

@ilmartyrk you proposed two possible solutions how to implement this technically. Please share (:

**Comment by loorm** [comment]
In the original feature request, I never mentiones closing the discussion. The feature request is about setting a pre-determined date, when topic moves to "In voting" status. Perhaps it's easier to think about it not as the "closing date" for discussion, but as a "starting date" for voting. So in voting system settings, you can both set the start and end date for the voting system. Right now, it's end date only.

This does not mean, that we couldn't discuss the idea of perhaps closing discussion, when a topic goes to the voting stage. In elections, for example, we stop campaigning on the voting day, so the idea has merit. But it's a separate idea, that wasn't part of my feature request originally.

**Comment by anettlinno** [comment]
If I understand you correctly, @loorm then we could solve this easily by providing Users opportunity to set up voting time under the voting "Deadline" with additions like "Voting starts" (date and time) and "Voting ends" (date and time). And when the day and time arrives, our system automatically moves the topic "In voting". 
Users can change and edit voting deadline under the "Actions" if needed. 
All participants and admin users could also get notification (if opt-in after the notifications feature is developed) if voting has started.

**Comment by anettlinno** [comment]
Triage 63. @kevincrepin this is an input to Voting component in redesign project.

- Add "Start voting" and "End voting" to deadline choosing option. There should also be explanatory text which explains that until the voting deadline arrives, users can only participate in the discussion. Then our system automatically sets up the voting and closes it after the deadline has arrived or when all votes are counted in (if applicable). 
- Admin user should be able to prefill the voting options for custom vote. User case: user wanted to prefill custom voting options with already know versions and then on the voting day she wanted to add few more options that were proposed during the discussion. Reason for that is that when organization uses our platform for general meetings for example, then prefilling the voting options helps to save quite a lot of the time. 
- Admin user should have an opportunity to change voting starting and ending time  under "Actions" any time.
- Once notification system is developed, admin user (and all other users who are invited into the topic??) will get notification if the voting started and ended

@loorm anything else? :)

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/49
