### ISSUE TITLE
Group similar Activity Feed items together

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#256]
**What is the problem?** When a topic becomes very active, updates from it swamp users' activity feeds (see image).

**Why is this a problem?** Users will not be able to see updates about other topics, since they drown in the mass of updates from the single active topic.

**Possible solution.** Group identical feed items together in activity feed, indicating their amount with a number. 

<img width="802" alt="Screenshot 2019-05-07 at 22 39 43" src="https://user-images.githubusercontent.com/22661743/57369124-8364d500-7195-11e9-9c58-06508200055b.png">

**Comment by loorm** [comment]
Triage #4 - reproduced. Need a UX/design for this. Can have a look at how other social media sites have solved it. Prioritized.

**Comment by tiblu** [comment]
@loorm Moved to "In preparation" as it misses the UX.

**Comment by loorm** [comment]
@kevincrepin Here's another issue, that needs your input. Work your magic on this, please?

**Comment by kevincrepin** [comment]
@loorm @tiblu Probably there are different criteria/exceptions as to when to group? Not only same "type", for example of a user voted yesterday on topic X and another user votes today on topic X, do we group these as well? Otherwise in this case every new notification would be grouped with  older ones and will be easily missed. So I think we need to define a period of time as well? For example all similar notifications that were created within x hour(s). Or "since you last visited" or something.

Attached an example of how it could look. In the case that there are a LOT of similar notifications, then the expanded view can still take up a lot of room, but at least it's a choice then.

![activity feed - grouping](https://user-images.githubusercontent.com/26792281/66394179-0efcbf00-e9dd-11e9-9f77-f296e667c0a7.png)

**Comment by loorm** [comment]
Triage 16. This design is relevant for solving #342 as well.

**Comment by ilmartyrk** [comment]
@oksks what do you think, should we create new strings for groups or would it be ok to just leave user name out from the main item text?
![activity_feed_groups](https://user-images.githubusercontent.com/19904307/75675088-1cb62800-5c8f-11ea-9e2d-1a9664c85af6.png)

**Comment by oksks** [comment]
I really enjoy the FB's solution:

> User **Ilmar**, **Liina Guiter** and 12 others have added an argument for topic **SEE ON HÄÄLETUSE TEST**

**Benefits:**
- The user has an overview of the most recently voted people immediately (since the most recent two names are written out)
- It looks "human"
- It's easily adaptable to any language without having to resort to robot-speak or improper declination due to genders and/or numbers. I can't think of another, better, option to address all of these at once.

@ilmartyrk @kevincrepin WDYT from UX & dev perspective?

**Comment by ilmartyrk** [comment]
After playing around I have found that there could possibly be issues with some groups. For example. if a person updates multiple fields of a topic at a time, it is all saved as a one activity, but for better understanding we currently brake these into multiple activities, each displaying the changes where possible. But now when grouping together the first issue that I encountered is that there were groups that had description _User "Ilmar" and 3 others updated topic "Example Title"_ and under there in the view all users list all activities were listed with Ilmar and had same time. I got around this issue by grouping changes to different fields. But there still could be cases where groups can contain activities by only one user, but during different times.

@oksks @kevincrepin , do you have any ideas how to get around this? Only idea that I have is to remove name from group description and display something like, _There were 3 changes made to field description in topic "Example topic"_. And under dropdown display all changes

**Comment by kevincrepin** [comment]
If we have this situation then I'd still rather see _# users have made changes to "example topic"_

Communicates better that the changes were done by users and not some generic entity :)

**Comment by ilmartyrk** [comment]
@kevincrepin @oks @loorm , but what do you think, should we then count the number of users not activities, I mean if dropdown contains 5 items, but actual users who are behind these acitivities is 2 should the activity text be  _2 users have made changes to "example topic"_ , that would mean that we need extra key if only 1 user did 5 activities etc.

**Comment by ilmartyrk** [comment]
So after going to different possible groups with real data, I have found  that with current solution there will be weird groups that contain activities by only one user. I believe that the best solution would be to group these activities differently. Instead of displaying text as: _"User and x others"_ I could group them as User has made x number of changes. And in the list try to display each activities description or username if for example User added 3 different users to a topic. Still it doesn't solve the case that if an activity is not in a group it could have better description if user updated a field with new value or wich permissions user was added with. Should we make this content also visibile inside group list @kevincrepin, @loorm ? 
![Capture3](https://user-images.githubusercontent.com/19904307/76861496-5d07cf80-6865-11ea-809d-2f6a0aae7921.PNG)
![Capture5](https://user-images.githubusercontent.com/19904307/76861499-5e38fc80-6865-11ea-804d-8be3421372f8.PNG)
![Capture](https://user-images.githubusercontent.com/19904307/76861500-5ed19300-6865-11ea-9db0-b15949f7c229.PNG)
![Capture1](https://user-images.githubusercontent.com/19904307/76861502-5ed19300-6865-11ea-81df-36408e5201e1.PNG)
![Capture2](https://user-images.githubusercontent.com/19904307/76861504-5f6a2980-6865-11ea-8055-a9df55fbf626.PNG)

**Comment by ilmartyrk** [comment]
@oks, @kevincrepin I've updated grouping so that there are two different types of groups, one type is when user has made similar actions and other is the old way of different users doing similar activities. Also changed the content to be more informative. What do you think, is it ok ?
![Capture](https://user-images.githubusercontent.com/19904307/77330734-6d69ef80-6d28-11ea-8bbb-21cd270f20c7.PNG)
![Capture1](https://user-images.githubusercontent.com/19904307/77330738-6e9b1c80-6d28-11ea-99a0-52b6037f352b.PNG)
![Capture2](https://user-images.githubusercontent.com/19904307/77330739-6e9b1c80-6d28-11ea-804e-d574c8fc3358.PNG)

**Comment by kevincrepin** [comment]
@ilmartyrk for me this seems to cover many, if not all, cases. So looks good for me.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Solution looks good. Tested. Confirmed working for the most part. A few minor issues created as separate Github issues.
