### ISSUE TITLE
Topic doesn't list all users who have access to it + other issues

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#260]
**What is the problem?**
I've noticed an unknown user "Lydia" has posted in our COS internal, private [topic](https://app.citizenos.com/en/topics/f87741fa-db6d-46b5-8f1d-9586cd0679a3?argumentsPage=1). I knew for sure, that we don't have a team member called Lydia.
<img width="779" alt="Screenshot 2019-05-09 at 15 55 59" src="https://user-images.githubusercontent.com/34126353/57456646-99969200-7276-11e9-8519-c2c2bda54c80.png">

I've checked the users' list under topic settings - she wasn't listed there either, only COS team members were - the topic belonged to COS team group. 

Having checked the groups topic belongs to, I did see 2 groups: 1) Citizen OS tiim, and 2) group called "()" with an unclickable name, which had a Read access. It's probably DUX group, but DUX groups members weren't shown to me under topic users.
<img width="827" alt="Screenshot 2019-05-09 at 16 09 17" src="https://user-images.githubusercontent.com/34126353/57456968-4f61e080-7277-11e9-9bc1-84fe3823e329.png">
At the same time, Kevin, who belongs to the DUX group, was able to see Lydia and himself in the topic users list.
When Kevin removed the topic from group DUX, the users' number shrunk by 1 to 11, and groups from 2 to 1, however Kevin, who (I'm not 100% sure but around 95%) wasn't listed in the users' list earlier, appeared amongst the users, as he also had a personal invitation from Liina.
![screenshot-app citizenos com-2019 05 09-16-45-39](https://user-images.githubusercontent.com/34126353/57458643-60f8b780-727a-11e9-9366-86e0055d3b46.png)

**Why is this a problem:**
1) Topic's user list should at all times display ALL users, who have access to a certain topic, to avoid confusion
2) User list should be shown identically to all topic's members, regardless of your background/belonging to a certain group.
3) Groups, that the topic belongs to, should be listed with their real names (DUX in case of the other group, while it was shown as "()"), and users maybe should have a group's avatar next to their name to indicate their origin.

**Comment by oksks** [comment]
[Slack conversation](https://citizen-os.slack.com/archives/C91AYDJ91/p1557406490003200) about this.

**Comment by ilmartyrk** [comment]
I actually checked at the same time and Lydia was displayed on users list.

**Comment by oksks** [comment]
Gah, I wish I took a screenshot of it :(

**Comment by loorm** [comment]
Queueing this for Triage #4

**Comment by loorm** [comment]
Triage #4 - cannot reproduce user missing from the list. Kevin had admin rights in topic, thus he could add DUX group to this topic, this is by design. The only (possible) problem is a nameless group, as shown in screenshot.

Tried to reproduce adding a nameless group. System did not allow this, responded with error message.

Added users to existing topic via another group by admin member - everything worked as designed.

Development needs to look at possible nameless group issue (screenshot above). Perhaps DUX group specific issue. 

issue by: @oksks

**Comment by tiblu** [comment]
![image](https://user-images.githubusercontent.com/7405383/58006418-b772bb00-7af0-11e9-937a-0af83edf6577.png)

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by tiblu** [comment]
TODO:

- [x] Take `({{level}})` out of the translation so that translation is more universally usable.
- [x] MK translation is wrong `"LBL_INACCESSIBLE_GROUP": "група",` - does not reflect the "inaccessible part"

**Comment by tiblu** [comment]
Fixed. 
@oksks Problem of translation was caused by the source having `&lt;` and `&gt;` in it, which in Crowdin render to `<` and `>`. Now, when a translation has `<` or `>` our translation script iterprets it as HTML code and puts it in as tags, not text.
I removed the `<` and `>` from the translations, as they are design element and moved the design parts into code.

![image](https://user-images.githubusercontent.com/7405383/81830685-107b0080-9545-11ea-999d-c6e976d6616c.png)

**Comment by loorm** [comment]
The issue was, sadly, never reported here on Github, therefore unable to test.

@oksks Please test and confirm if whatever the issue was has been fixed.

**Comment by oksks** [comment]
@loorm Will gladly test - could you pls specify, which issue you refer to as never have been reported on Github? And what was fixed - what should I test exactly?

**Comment by loorm** [comment]
@oksks Pls look at comment by @tiblu from May 13. He writes about some problem of translation. The problem itself is not clear, therefore I don't know what you discussed or what should be tested to see, if it was fixed.

**Comment by oksks** [comment]
@tiblu - I'm afraid the exact problem isn't clear from the description and thus I'm not sure how I can test it - pls advise steps to verify, or maybe test yourself as you've reported it?

**Comment by tiblu** [comment]
This happens if you view a Topic member list which has a Group member AND the viewing User does not have access to that Group.

Reproduce:

* As User A, invite User B to a Topic as admin
* As User B invite a Group with members (User C, User D...) to the Topic.

Result:

* User A got the bug mentioned above, as he/she has no access to the Group and SHOULD NOT see group name under the member names (User C, User D)

**Comment by loorm** [comment]
@oksks Can you please recreate from the above steps and verify, that fix is working?
