### ISSUE TITLE
BUG: Login/signup pop-ups get blocked by ad blockers

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#264]
**What is the problem?**
There are reports that ad blockers block our login pop-ups.

**Why is this a problem?**
Users that use ad blockers cannot log in.

**Possible solution.**
We implemented the pop-up model to support AFoorum widget. We MAY want to use redirect model for app and pop-up for widgets IF there is no way of get around ad blockers.

**Comment by loorm** [comment]
Triage #5 - Margo will investigate specific use case. Report came via Anett.

**Comment by loorm** [comment]
Report came via Anett from a US user. Report was: "I have an ad blocker installed as an add-on to Firefox (which is my preferred browser). Apparently the ad blocker interpreted your popup messages as ads. After I disabled the ad blocker for your url, everything worked fine."

**Comment by loorm** [comment]
I have asked the following from the reporting user: ""We are trying to replicate your ad blocker login error on Firefox. It is important for us to be able to replicate the error, otherwise we can't fix it. Can you please tell us, which adblocker you are using - is it the Firefox built-in blocker or a third party app? Could you please describe what happens in a few more details or possibly provide screenshots? We would really appretiate this, since we have not had this bug report from anyone else. Howver, it is of high priority, if it prevents users from signing into Citizen OS."

**Comment by tiblu** [comment]
@loorm Did you get a response with details from the User?

**Comment by tiblu** [comment]
**DONE!** App uses redirect model, widget uses pop-up model.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
