### ISSUE TITLE
On a smallish screen, log-out link on the menu is not visible 

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#299]
**What is the problem?**
Logout option is hidden on a smallish screen and the menu on the left is not scrollable. If the screen is  also narrow, then UX switches to the hamburger menu in the top right corner. But if the screen is smallish, but not small enough to switch to hamburger, then logout may be hidden from view.

**Why is this a problem?**
Difficult for a user to log out, if the log out option is nowhere to be seen.

**Possible solution.**
N/A

<img width="607" alt="logout" src="https://user-images.githubusercontent.com/22661743/67683894-da0bd880-f99a-11e9-91ef-aa19d8f822c5.PNG">

**Comment by loorm** [comment]
Maybe this is such a niche use case, that we will not do anything about this. Maybe, there is a solution, which in proportionate in time to the rarity of the use case. Thoughts @tiblu @kevincrepin?

**Comment by loorm** [comment]
Triage 14 - bug reproduced. @kevincrepin - please debate solutions with @tiblu.

**Comment by kevincrepin** [comment]
@tiblu Probably the solution that will work the best in most if not all situations is just not having the sidemenu as a fixed height element, but give it the same height as the page. And just under the menu items it extends with the dark grey colour. Like in attached screenshot.

![Screenshot 2019-11-04 at 12 33 13](https://user-images.githubusercontent.com/26792281/68114680-4c326f00-feff-11e9-9f94-bf57cac1a37c.png)

**Comment by loorm** [comment]
This has now become an issue in my very normal 1920x1080 screen.
![Capture](https://user-images.githubusercontent.com/22661743/74224492-a3479d00-4cc1-11ea-8fd2-67b8be2aafef.JPG)

**Comment by kevincrepin** [comment]
I stand by my previous (possible) solution. Could even be done so that the menu only scrolls within the height that it has, so if you scroll down on a long page, you don't scroll far away from the menu. It's flexible to scroll within its own height...If that makes any sense :D

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by tiblu** [comment]
I think what Kevin means is:

```
nav {
   ...
   overflow-y: auto;
   overflow-x: hidden;
}
```

BUT, that would need testing with different screen sizes.

**Comment by tiblu** [comment]
@kevincrepin @loorm 
Done, implemented the quickest fix I could come up with - menu will have vertical scroll if it does not fit on the screen. It does look a bit funny when in mobile view and small height on desktop, but I would think it's very unlikely to happen.
If the fix is not good enough, we need to invest more time to it.

![image](https://user-images.githubusercontent.com/7405383/82202836-2a349300-990b-11ea-9a6a-b9120dd84548.png)

**Comment by kevincrepin** [comment]
Not really what I meant :) The side menu should just scroll together with the other content. So if some items don't fit on the screen, you will see them when you scroll down. Nothing fancy, very regular.

**Comment by kevincrepin** [comment]
Like, it's all part of the same scrollable content.

**Comment by tiblu** [comment]
@kevincrepin So, if you scroll down, the menu will not be visible at all. I was thinking it is causing annoyance to 90% users while the extra scroll of the menu would annoy probably 1% users? The menu scrolling out of view would annoy the most on dashboard.
BUT, if that's what you think is best, it can be done.

**Comment by kevincrepin** [comment]
Not sure about annoyance since this is a lot more understandable and common behaviour. Also we can't just hide functions, they have to still be accessible, annoyance be damned :)

Yes, It leaves a lot of blank space on the left, but the next step would be that the side menu does scroll down as you scroll down the content, but once it reaches the last menu item, it will be fixed there. It's a bit difficult to explain, so I made a very quick example:
https://www.dropbox.com/s/5rfpi7wdr9jyc1p/scroll_ref.mp4?dl=0

**Comment by kevincrepin** [comment]
Also this is why in the next design there won't be a side nav anymore :)

**Comment by loorm** [comment]
A lively discussions for a closed issue :)

I think current solution (menu scrollling on it's own) is ok, since this case is relevant for very few users, AFAK.

I'd say - tested, confirmed the menu scrolls. Keep the issue closed.
