### ISSUE TITLE
Enable account termination by user.

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#318]
**What is the problem?**
User cannot delete their own account.

**Why is this a problem?**
If you have an option of starting to use something, you should always have an option to stop using it and request to be forgotten.

**Possible solution.**
This flow already exists for cases, when user does not agree to updated Terms of Use. Create a button in profile dialog, that would initiate the same flow.

**Comment by loorm** [comment]
Triage 15: if this is really one button, time estimate is 1 day. @kevincrepin - please create and put this button somewhere. Also, we probably need warning dialogs with copy texts?

**Comment by kevincrepin** [comment]
https://projects.invisionapp.com/d/main#/console/17224475/395326027/preview

I created a version for our current dialog windows, BUT we already know that they are not ideal and when we look at the profile dialog, it could also use some rethinking. So that's what I did with the dialog windows under our current one. Action to edit (or delete) are below the info. Editing takes you to a screen where you can change all the data and start the reset password flow.

We definitely need a confirmation dialog and I would reuse the same as we use for deleting a topic: https://projects.invisionapp.com/d/main#/console/9829159/210112087/preview
We just need to rewrite the copy to indicate the consequences.

**Comment by loorm** [comment]
@kevincrepin Can we get some updated view links on this, please? We actually already have account termination API flow and I know you have the visuals. So finishing this should be quite rapid.

**Comment by kevincrepin** [comment]
The account dialog: https://projects.invisionapp.com/d/main#/console/9829159/404592934/preview

confirmation dialog should be similar to delete topic (top right), with different copy: https://projects.invisionapp.com/d/main#/console/9829159/418066154/preview

**Comment by loorm** [comment]
Assigning for Triage 23 on June 8.

**Comment by loorm** [comment]
Triage 23. Ready for development. Prioritizing. Estimated dev time 1 day.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
