### ISSUE TITLE
Topics are non-printable

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#330]
**What is the probem?** I was viewing this public topic (https://app.citizenos.com/en/topics/ac46ba58-bcb6-468b-9c51-961890d00b90?argumentsPage=1) on Chrome. Not in edit mode. Pressed CTRL+P. The resulting PDF is attached. It isn't pretty.

**Why is it a problem?** Many societies still work on paper. Digital divide. If it doesn't print, it probably isn't readable for screen readers (disabled people). Lot of reasons.

**Suggestions for fixing**
N/A
[Citizen OS - an e-decisionmaking platform for communities_.pdf](https://github.com/citizenos/citizenos-fe/files/3819654/Citizen.OS.-.an.e-decisionmaking.platform.for.communities_.pdf)

**Comment by loorm** [comment]
Triage 15. We want to print both topic content and discussion, with logo in top left corner. Mikk says this requires separate style sheets. Mikk successfully replicated. No time estimate right now. Must be investigated.   

**Timebox to 1 day.**

**Comment by tiblu** [comment]
The dependency of #392.

**Comment by tiblu** [comment]
Done! 

As there were no clear guidelines how much to print I did what I tought is good.
All topic contents is printed. 
Arguments are NOT printed.
QR code added to the bottom of the page that reflects the url the print was initiated on. So if you are printing the voting page, a direct link to voting page is in the QR.

For the v3 we should have extra designs that reflect printing views.

![image](https://user-images.githubusercontent.com/7405383/76869873-9c3c1d80-6871-11ea-8692-a82145e49ee6.png)


[print_test.pdf](https://github.com/citizenos/citizenos-fe/files/4344125/print_test.pdf)

**Comment by oksks** [comment]
Just tested this - some comments:

- Maybe it's worth including topic status, categories and authors, too?

- It looks like a simple document when printed - no indication, that it's a topic from some platform where  people could take action on it. Maybe it could have a message in the header a'la: This topic "TOPICNAME" lives on e-democracy platform Citizen OS. Come check it out or voice your opinion on other topics!

- PDF file is saved as "Citizen OS - an e-decisionmaking platform for communities_.pdf" - could it have topic name as filename? or "TOPICNAME - http://app.citizenos.com"

- Can we shorten URLs somehow? For folks who have no idea, how to scan the QR code and would need to type the URL in

- Agree with Anett's proposal (in Slack), that it would be great to have an option to print the topic WITH arguments - since we don't allow categorizing them, in case there are hundreds of arguments, it will be necessary to print them them out and colour-code or annotate.

Attached the topic in PDF exactly as it came out from COS, as an example.

[Citizen OS - an e-decisionmaking platform for communities_.pdf](https://github.com/citizenos/citizenos-fe/files/4344470/Citizen.OS.-.an.e-decisionmaking.platform.for.communities_.pdf)

**Comment by tiblu** [comment]
@loorm What do you think, shall we call it good for now and consider all  the proposals for COS v3 or we're going to do something extra with current version?

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.

@tiblu - we call it good for now.

@kevincrepin - please look at suggestions by Oksana above. I don't know if you have thought about printing when envisioning our future, but it would be good if we had improved printability and most of the suggestions by Oksana are good food for thought.
