### ISSUE TITLE
Red internet connection alert is constantly active 

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#352]
**What is the problem?**
Red internet connection alert is active even when I´m connected and platform works.

![image](https://user-images.githubusercontent.com/45175679/69541888-ec296880-0f92-11ea-971f-1c3de8d6740f.png)

**Why is this a problem?**
It does not affect using the platform, but it´s annoying to see the alert every time the page is being refreshed.

**Possible solution.**

**Comment by loorm** [comment]
Triage 16. This bug was created when fixing a previous issue of showing error messages too briefly.  Probable solution - didvide error msgs into two categories. On reconnect wipe "connection error" msg, keep the others. Possibly browser sends connection re-established status, so no need to poll.

Replicated. Opening activity feed, even though not a full page reload event, removes the error message (reason unknown). Other in-site navigation actions do not and the message remains.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
