### ISSUE TITLE
Topic invites - confusing user experience when opening a regular topic link, but haven't accepted invite

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#360]
**What is the problem?**

* A person has invited me to a topic.
* A person has sent me a direct link to that topic in e-mail with extra instructions. For ex: https://app.citizenos.com/en/topics/cb6a3007-6e1d-451e-bd66-c7d11ee0a3d8
* When I open up the link, I get "Permission denied", which is because I have not clicked the "Accept" link in the invite email.

**Why is this a problem?**

Confusing, people may think the permissons are not set properly, but actually you cannot access the topic if you havent accepted an invite.

**Possible solution.**

* **TODO: Needs discussion**

**Comment by loorm** [comment]
Triage 16. In an ideal universe, we will help the user understand, that they need to accept the invite first and then proceed to the topic. In the current universe, this task will be postponed until further notice. Dev estimates this to be time-heavy.

**Comment by loorm** [comment]
This is a rare use case, that our help documentation and customer support can address. There is no good user flow for this. It actually makes sense, that you cannot access the topic via the link before accepting the invite, because the app does not know, who is clicking the link and whether they have a pending invite or not.

Perhaps, we can help the user by creating a custom "Permission denied" page for topics (like the one I mocked up below) instead of the generic one we are showing right now. @tiblu - can we do this? 

![no_permission](https://user-images.githubusercontent.com/22661743/83002627-f564c200-a015-11ea-9040-8b740fac24dd.jpg)

**Comment by tiblu** [comment]
@loorm I think this error message is a good idea.

* Implementing this extra message for topic pages is quite simple - 2hrs.
* In addition to first, implementing a solution, where IF you are logged in AND get a permission error AND have a pending invite you would be redirected to accept the invite - 4hrs.

That is 6hrs in total if we do both.

**Comment by loorm** [comment]
Replicated. Currently, red bar at the top of the screen and grey text in the middle are shown. There is no blue text. We have a solution, copy and time estimate (6 hrs). This is ready for prioritization. Moving to Triage.

**Comment by anettlinno** [comment]
Triage 45. Send to development.

**Comment by KatiVellak** [comment]
Legally reviewed, good and clear solution.
