### ISSUE TITLE
Topic sharing rights in private group

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#530]
**What is the user story?**
Only the owner of the topic has the right to share topic with other people (inviting users). Group members (admins) often need to invite users on this topic, but they are not allowed to do so.

<img width="947" alt="Don´t have permission" src="https://user-images.githubusercontent.com/45175679/86014213-b4066e80-ba28-11ea-86f3-826d9e0eed37.png">

**What is the requested feature?**
Please allow topic admins to invite users on the topic;

**Additional information.**
(:

**Comment by loorm** [comment]
Triage 24. Replicated. However, this is not a bug or a feature. This is by design.

1) If topic author wants group members (admins) to have a right to invite users, he/she needs to give the group admin rights.
2) If topic author does not want group members (admins) to have a right to invite users, he/she needs to give the group edit rights.

Closing issue.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
