### ISSUE TITLE
A personal dashboard

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#561]
**The public topics being discussed on the Citizen OS platform are mainly of interest to a specific group of people, not to everybody. For that reason, the platform dashboard could be catered towards the needs of that user. The dashboard could be more visual and interesting to the user, if it showed them the topics only relevant to them (or at least highlighted relevant topics) and showed how many likes / arguments / edits by others the topic has received since they last visited. This would give the user incentive to come back and check the notifications the topics have received. Throughout a difficult project process it is encouraging to visually see the progress a topic has made. Making the dashboard more relevant to the user (and more interactive /fun) could make them want to use the platform more.**

**Comment by loorm** [comment]
Triage 25. We discussed this and a few questions came up for @liinaguiter :
- Would this replace the current public topics view or is this an enhancement of current "My topics" view or is it something completely new you are proposing?
- How is it different from the ability to "pin" a topic in My topics view?
- Do you think the system shoudl determine user's interest automatically or based on user input (like pinning / favouritiing a topic)?
Needs a more detailed feature description and discussion, then UI/UX development.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by liinaguiter** [comment]
@loorm Good questions! This idea was about something completely new.

**Comment by loorm** [comment]
I was unable to filter out a new user story here, because:

- "The dashboard could be more visual and interesting to the user, if it showed them the topics only relevant to them (or at least highlighted relevant topics)..."
Solution to this is to "Pin" the topics you are interested in. This functionality currently exists. 

- "... and showed how many likes / arguments / edits by others the topic has received since they last visited. This would give the user incentive to come back and check the notifications the topics have received. Throughout a difficult project process it is encouraging to visually see the progress a topic has made."
There are actually two existing solutions for this. 1) Activity feed. Everything that has happened in your topics since you last visited goes into the activity feed - all the votes, edits, arguments, everything. 2) If you want to see this for a specific topic, then there is the "Actifity feed & notifications" under the topic data in "My topic" view. From there, you can get all the updates related to that specific topic. 

Perhaps there is a user story here that I missed. As things stand, I think our existing functionality covers everything that was described. I will close the issue, but if I missed something, please point it out and we can reopen.
