### ISSUE TITLE
For Estonian NGO's to use for online meetings, need a eID signed list of attendees.

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#577]
Our User (Raul Kübarsepp) reported, that for Estonian NGO's to use COS for online meetings, they need the function of eID signed list of attendees. Then, the decisions would be valid in the eyes of the law.

Could ask for advice on how to best solve this from Raul Kübarsepp or Alari Rammo for example. 

Raul Kübarsepp believes if this function is created in COS, the use in NGO's will go viral.

**Comment by loorm** [comment]
Triage 27. Based on the current description, all necessary functionality seems to exist. We need to clarify, what is missing. Moving back to "In preparation" until we have had a chance to clarify.

**Comment by liinaguiter** [comment]
I explained to the user Raul Kübarsepp, that you can list the people in a topic and sign that topic. 

But he sais that something more is needed: 

"Spetsiaalne nupp "allkirjasta dokument" vms.
Kui olen mingis teemas, siis paistab ainsana nupp "alusta hääletus", aga hääletused ole ole seltside ainsaks tööriistaks.
Kui mõtlema hakkan, siis, "allkirjasta dokument" on vajalik  gruppide vaates.
Muidu peab selts ikkagi kasutama dokobiti vms tasulist teenust, et digiallkirjastada dokumente."

**Comment by cyberSmi7h** [comment]
Yup, we need common document signing feature most.

**Comment by liinaguiter** [comment]
"Kas Sa mõtled, et oleks vaja sedasama funktsionaalsust nagu Digidoc või docobit, st. et saad digiallkirjastada? 
Meil saab allkirjastada ning see on äriregistri poolt aktsepteeritud, lihtsalt pead enne hääletama dokumenti, siis saad allkirjastada. Ei saa ainult allkirjastada.

9:39 AM
Raul Kübarsepp
Täpselt. Olekski vaja eraldi allkirjastamist eraldi ja selge funktsioonina.
So allkirjastamist läheb vaja MTÜl igapäevaselt, hääletamist paar korda aastas.

Docobit on tasuline.

**Comment by loorm** [comment]
I understand the problem, that users have. Unfortunately, Citizen OS was not created to solve that problem. The reason we are willing to pay for our users' digital signatures (and make them free to the users) is that we want more people to decide things collaboratively. Documents can be signed by single people or a selected few. Citizen OS is a collaborative decisionmaking tool. Therefore, voting first and then signing will remain the user flow, because this fulfils our vision of what we are, the kind of world we want to help create.
