### ISSUE TITLE
Private topic "lock" icon confuses users

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#659]
**What is the user story?**
The user who accepts the group invitation and logs in will land on the groups page. If they click on the "+" mark they see the topics in group but private topics have closed "locks". Users get confused and think that they cannot participate because the topic is locked. When they click on the topic, they will see the topic´s general information (on right) but not the content nor the voting. If they click on the "activity and notification" they only see the activity feed information. If they click on "Current voting results" they still cannot see the topic or vote and that´s why they think the topic is locked.

<img width="827" alt="Locks" src="https://user-images.githubusercontent.com/45175679/112016965-db144b80-8b35-11eb-9652-ea3ff4e5efca.png">

+ add screenshot / screencast when applicable

**Which feature needs to be updated and how?**
Change private topic "lock" icons for something else (or just "private topic" and "public topic"
When landing on the groups page, user should see the topic content and voting button on the right side (where currently is topic´s general information). OR with only one click on the topic, user should get into the topic content and voting.

**Additional information.**
N/A

**Comment by loorm** [comment]
Triage 36. Understand, but this is not a problem of the lock icon. The problem is, people do no tunderstand, that they need to click the topic title on the left (or one of the two the edit shortcuts). @kevincrepin any ideas, please?

**Comment by kevincrepin** [comment]
On it tomorrow ;)

**Comment by kevincrepin** [comment]
I think these are two separate problems. Exactly the behaviour of clicking twice to get into the topic and separately the locked icon which confuses people.

The clicking twice problem is a recurring one and one I believe will only make fully sense with a change in layout because the current logic defines the layout. If the user would click on the topic on the left and immediately go to the full topic view, then what's the point of this big space on the right where we currently show the data and feed. It would become quite useless. So yes, we could do it so that one click goes to topic and some other action shows the info on the right side, but it would look and feel quite weird.

One simpler way would be to have the voting possibility on the right (which is what Anett suggest if I understand correctly) and we had this in an old version but not sure if this was actually done so :)

![topic in voting](https://user-images.githubusercontent.com/26792281/116659110-bb284100-a999-11eb-9a2b-9237cda3099c.png)

About the locked icon. I can see why it's confusing. Having a label would clarify, only problem is that it's a word then and needs translating + different character amounts. Not sure in the current layout of this card how much of the title would be truncated. But maybe they should be able to go on several lines...

![Screenshot 2021-04-30 at 09 59 40](https://user-images.githubusercontent.com/26792281/116659879-e95a5080-a99a-11eb-8fb6-d95a4c19f930.png)

**Comment by loorm** [comment]
My final 10 cents on this is the following:

- Lock icon is just a feature of our UX. Different software has different icons to communicate things. Lock is a pretty common privacy icon. I would leave it as is. No first time user ever understands everything, if the software is even moderately complex. Look around at the Github page you're on? Would each of these icons intuitively make sense to a first time user? No. You learn to use your tools. The way the world works. We don't practice tooltip texts in our UX, but if we did, this would be a good place to use one. That's as far as I would be willing to go re the lock icon.

- Moving from "My topics" to the actual topic has been an issue ever since we started. Again, you learn to use it and the issue goes away. For beginner users, it takes a few times to get used to this.

In the future, perhaps "My Topics" view will not be split into two columns, but will instead list all topics in a single column. Underneath each title would be some info about the topic and then a "See more" link, which would open up the full info panel with data and feeds below the title. However, if you click the title of the topic in the list, you go directly to viewing the topic. But as Kevin said above, this is not a cosmetic change, this needs a redesign.

With this, I hand the issue over to @anettlinno.

**Comment by anettlinno** [comment]
Thanks for the comments and ideas, @kevincrepin and @loorm! 

I will close this topic as when sliding over the "lock" icon with cursor then user sees explanatory texts "private topic", "public topic" and I think this solves this issue.

I will open new issue to work with the topics layout and link it with this topic here so we would not lose the ideas :)
