### ISSUE TITLE
The display of counted votes is confusing

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#664]
**What is the user story?**
Voting results are displayed in two numbers, e.g. 6/11 and users do not understand what these numbers show. 

<img width="508" alt="counted votes" src="https://user-images.githubusercontent.com/45175679/112135853-eb303780-8bd6-11eb-831c-93db8524e2bd.png">

**Which feature needs to be updated and how?**
There could be exclamation or question mark icon and when user slides over the icon, it helps to explain what these numbers show.

<img width="336" alt="Explain" src="https://user-images.githubusercontent.com/45175679/112136268-6560bc00-8bd7-11eb-8082-abaa7360ede1.png">

**Additional information.**
N/A

**Comment by liinaguiter** [comment]
Strongly agree that adding info bubbles to many (if not all) features on our platform would help the user right at the place where they are stuck / confused. Hypothetically this will reduce the number of help requests to our customer support and increase the number of users because they do not give up. 

Another example of an info bubble design for insporation = )
<img width="403" alt="Screenshot 2021-03-23 at 15 39 39" src="https://user-images.githubusercontent.com/34899902/112156052-913b6c00-8bee-11eb-8d4a-000d631d426d.png">

**Comment by BeccaMelhuish** [comment]
I think a little question mark in a circle would be clearest for these help buttons.

**Comment by BeccaMelhuish** [comment]
My suggestion would be that the help bubble goes to the right of the "X/X votes counted" (where I have highlighted in yellow, but obviously realigned) and says the following:

"The number on the left shows how many people have voted so far. The number on the right shows how many people have joined the topic in total." 

If possible to have the Help Bubbles show different things for the admin, then when the admin of the topic clicks on it they should also see a line which says:

"It is not possible to see who has voted before the voting has ended. For more info see Q3 in our FAQs (hyperlinked 'FAQs')." 

And if everyone has to see the same Help Bubble then everyone should see that additional line, but with "Note to admins:" at the beginning of it. 

![image](https://user-images.githubusercontent.com/61320526/116083255-b7947180-a69c-11eb-8833-3c13c63bd212.png)

**Comment by loorm** [comment]
Triage 36. Rejected. This is only the case for private topics, in public topics it just reads "53 votes counted". It seems this is a case for a single user or from a time when we still had a confusion in multiple choice voting systems.  

Adding the proposed text to help documentation is good, we can do that. However, in order to avoid visual clutter, we do not support adding the question mark icon at this time.
