### ISSUE TITLE
Voting end time sometimes fails to be 00:00:00 the chosen day +1 

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#667]
Vote creating process allows users to only pick date not time. This ends in final time not being consistent throughout different votes. Although votes should default to creators time-zones 00:00:00 time eg. Estonian user chooses vote end date to be 23.03.2021 and it is saved into DB as 24.03.2021 00:00:00+02. But after taking look into values in DB it seems that there are some timestamps that don't fit into this model. Some examples:
2021-03-18 10:10:12.946+00
2021-03-15 11:04:06.102+00
2021-03-02 11:36:42.395+00

**Comment by loorm** [comment]
Triage 36. Confirmed. Needs to be fixed. Link to #590, because it makes sense to fix them together.

**Comment by anettlinno** [comment]
_Re to Ilmar: Vote creating process allows users to only pick date not time._ 
Lately, users have asked about the option to set a time for voting. It is essential in two user cases: 
1. NGO board have to publish general meeting agenda points with relevant documents at least 2 weeks before the general meeting. They want to allow people to read the documents and discuss over the agenda points, but they want to set shorter time period for voting;
2. For quick decisions. User wants to give opportunity for the NGO members to participate in important decision and wants to limit the time because the decision has to be done quickly and those who cast their arguments or votes later, are not being considered.

**Comment by anettlinno** [comment]
Link to #316 as this seems to be relevant for this issue.

**Comment by loorm** [comment]
@ilmartyrk I closed issue #667 after our meeting today. However, this current issue is about a possible bug (the weird voting end times you found in our DB). I'm leaving this open and sending it to Triage. Suggesting, that you allocate time for investigation. 

Possible idea - maybe voting ended by user closing voting manually (sending to follow-up). Perhaps the time recorded in DB is the time, when user clicked "Send to follow-up"?

**Comment by anettlinno** [comment]
Triage 46. @ilmartyrk is investigating this possible bug. Approx. investigation time 30 min.

**Comment by tiblu** [comment]
### Ways to create "weird" vote ending dates

* In the UI:
    * Create a Vote
    * Choose enable "Deadline" AND DO NOT MODIFY anything in the date fields.
    * Press "Start voting". DB will have "endsAt" date with milliseconds. Probably cause of the form default has no rounding. 
    * **ALSO:** When doing this, the "endsAt" will be earlier than the "createdAt", "updatedAt" BUT API validation passes.
* Use API directly, in this case "endsAt" can be any valid date with millisecond precision.

#### Other notes

* The date formats are inconsistent all over the place.
* The UX of entering deadline is poor.

#### Query

```
SELECT
    tv."topicId",
    t.title,
    v."updatedAt",
    v."createdAt",
    v."endsAt"
FROM "Votes" v
LEFT JOIN "TopicVotes" tv ON (tv."voteId" = v.id)
LEFT JOIN "Topics" t ON (t.id = tv."topicId")
WHERE
    v."endsAt" IS NOT NULL
ORDER BY v."createdAt" DESC
;
```

**Comment by tiblu** [comment]
### DONE

* Fixed the bug where default end date would contain milliseconds. Default end date is now next day 00:00.
* Unified date formatting - using locale based formats (`LL LT` etc).
* Note that you can still provide millisecond precision `endsAt` date in the API. This is by design.
