### ISSUE TITLE
Solution for FAQ 9: Why can't I log in through Internet Explorer?

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#705]
As discussed (@tiblu @ilmartyrk, 06.07) here is the issue to update the page that explains that you can’t access Citizen OS via Internet Explorer, when someone tries to do so, to help address FAQ 9. 

Notes from the meeting below, though you will have a better idea of what exactly you meant:
"Becca to create a Github issue to update list of supported browsers and make dedicated browser support page up-to-date re new restrictions. Check what happens when try currently." 

Though I just tried accessing the platform myself to see what happened and it worked fine! 

![image](https://user-images.githubusercontent.com/61320526/117492008-4d6bae80-af71-11eb-823e-eddb072be9ec.png)

**Comment by loorm** [comment]
Triage 37. Confirmed major problems, when using app via IE11. Did not land on unsupported browser page, though. @ilmartyrk extended unsupported browser (unknown device view, if clause within index.html) page to include IE 10 and IE 11. @BeccaMelhuish  to create an updated text for the page. Also need to think about translations, currently in EN / ET / RU only. Prioritizing.

**Comment by BeccaMelhuish** [comment]
Hi @ilmartyrk could you send me a screenshot of what the page currently looks like, and details of anything that needs to be changed, then I will update the copy for it :). (It still let's me log in just fine with IE, so I can't see the unsupported browser page myself).

**Comment by ilmartyrk** [comment]
@BeccaMelhuish https://app.citizenos.com/views/unknown_device.html

**Comment by BeccaMelhuish** [comment]
Thanks @ilmartyrk! 

I feel like this page could also use a design from @kevincrepin too, perhaps? So that it looks a bit more professional/more in keeping with the COS platform, and also perhaps just one button to "update your browser", seeing as they all go to the same link?

Re the text, is it possible to have two versions - one that is shown for those trying to use Internet Explorer, and one that is shown to anyone trying to use an old version of any of the other browsers? If so I'll write you two different texts, to keep everything relevant and understandable for all cases :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish currently we only detect for IE version les than 9 using the special IF condition `<!--[if lte IE 9]>` but that has been dropped in the later versions of IE. I am going to have to make a new browser checking script that could possibly be compatible with with other browsers too. My only concern now is if and how to make it translatable. As the current page is so "ugly" because we cannot run angularjs in older browsers and use it's translating mechanism. We could also use html template translating like in e-mails but then we would need a language selector for this page.

Also here is a screenshot of IE and how the page actually looks there
![unknown browser](https://user-images.githubusercontent.com/19904307/119992281-0bafb000-bfd3-11eb-9241-0d250808b657.jpg)

**Comment by ilmartyrk** [comment]
NOTE: Found that I can use node.js side browser detection and can serve page from server-side. This allows more flexibility with handling these requests and redirects. An example middleware code for implementation
```
const browserDetect = (req, res, next) => {
    var ua = req.headers['user-agent'];

    var msie = ua.indexOf('MSIE ');
    if (msie > 0) {
        // IE 10 or older => return version number
        var IEversion =  parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
        console.log('IEversion', IEversion);
        res.sendFile(__dirname + '/public/views/unknown_device.html');
        return res.set('Permissions-Policy', 'interest-cohort=()'); // Opt-out of Google FLoC
    }

    var trident = ua.indexOf('Trident/');
    if (trident > 0) {
        // IE 11 => return version number
        var rv = ua.indexOf('rv:');
        var version =  parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
        console.log('IE 11');
        res.sendFile(__dirname + '/public/views/unknown_device.html');
        return res.set('Permissions-Policy', 'interest-cohort=()'); // Opt-out of Google FLoC
    }

    var edge = ua.indexOf('Edge/');
    if (edge > 0) {
        // Edge => return version number
        var edgeVersion =  parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
        console.log('EDGE', edgeVersion);
    }
    // other browser
    console.log(ua);
    next();
}
```

**Comment by ilmartyrk** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection#request-an-update-to-the-ie-compatibility-list

**Comment by ilmartyrk** [comment]
Triage 38, wait until we are added into Microsofts IE to edge sites list. When added, test and confirm. If working close issue.

**Comment by BeccaMelhuish** [comment]
Hi @Ilmar! Sorry I got a bit lost here, but if you let me know when all you've resolved it as you're planning to then I can take a look and see if I feel any tweaks would be helpful re the FAQ?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish as it needs quite big update from our side and most of the users this features is intended for use Internet Explorer, we decided to add our site to the list of websites that will be automatically opened by Edge browser if opened with IE. 

The reason behind this is that we never have intended to have our working with so called exotic browsers, its good if it does, but to check and maintain a list of browsers for small amount of users is currently not the most optimal way to use our resources. We decided to re-open this issue if turned out that there is some new browser that is used by a certain bigger user group that is interested in our app AND if that browser has some issues with earlier versions and our app not working properly. 

I am now closing this issue as our app.citizenos.com has been added to microsofts sites list

**Comment by BeccaMelhuish** [comment]
@ilmartyrk OK great! In terms of the FAQs it was all about Internet Explorer, so as far as that's concerned this sounds like it's fixed :) However I just tried to access app.citizenos.com using internet explorer and nothing happened - I could access the platform just fine in IE without it opening in Edge.. Should it already be redirecting?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish , I've checked this thing, it seems that for it to be correctly working, user needs to install updates, this file seems to be siting inside users computer in order to work. Anyway I re-opened this issue, for further discussion. 
  1) Do we need to assume users update their software regularly and thus close the issue
  2) If we assume users who use IE don't update their software because they don't want to, will we implement our own solution with updated design

**Comment by loorm** [comment]
Triage 39. Bring our old browser warning page back into use. Leave it in the three languages as is, will not translate. Add analytics code, to be able to see, how often this page gets served. Est. dev time 3 hours. Prioritizing.
