### ISSUE TITLE
Important topic changes do not show up in activity feed

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#715]
**What is the problem?**
Changing some important topic attributes do not show up in activity feed. 
- [x] changing topic visibility (private to public or vice versa)
- [x] sending topic from voting to follow up. NB! When you change from in progress to in voting, it shows up twice in activity feed, as it should. Once, as a topic status change action and once as voting started action. Therefore, going from in voting to in follow-up should also show up twice - once as status change (blue icon) and once as voting ended (green icon). 
- [x] sending topic from in follow-up back to in voting
- [x] sending topic from in follow-up to close topic

**Why is this a problem?**
If a private topic accidentally becomes public, then other users of the same topic can see it in their activity feed and can alert the admin. Making visibility change transparent in activity feed prevents mistakes.

**Possible solution.**
Add visibility status change to activity feed.

**Comment by loorm** [comment]
Triage 37. Estimated dev time 6 hours. Prioritizing.

**Comment by ilmartyrk** [comment]
This was broken because of a sequelize update. Instead of using `Model.update` and after running the `updateActivity` now the logic is to get instance from database, use `instance.set` on fields that are allowed to be updated and inside transaction first run `updateActivity` and after that `instance.save`
