### ISSUE TITLE
Slug support - fetch Topic by slug

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#72]
Human readable slug support needed in API because:

Emails need to have urls with slugs
API will still use the system ID, but way may need to move to BIGINT id-s from UUID because the "slug+ID" would look really long and awkward.

Related tasks:
* https://github.com/citizenos/citizenos-api/issues/8 - FE work

**Comment by ilmartyrk** [comment]
This issue has been raised in the SEO context too. Couldn't find where. @liinaguiter maybe you remember where? Anyway sending this issue to prioritization,

**Comment by anettlinno** [comment]
Triage 50. This topic needs further discussion as this is rather decision of principle. @liinaguiter @BeccaMelhuish. Moving back to In prep.

**Comment by ilmartyrk** [comment]
Adding an example form ERR. This link uses slug, but it works even if the text part is removed and only number remains 
https://www.err.ee/1608392666/tarbijahinnad-tousid-aastaga-seitse-protsenti
Our solution would look similar. If we decide to keep current ID system URLs will probably go too long. If we replace them with a number format it will need changes in database structure and we will need to have backward compatibility

**Comment by anettlinno** [comment]
I talked to @liinaguiter and @BeccaMelhuish and decided that this change is not that important for SEO for following reasons (copied from Slack): 

- URL names are important for websites that are searched for, but COS topics are either shared via social media / email / email list or directly from person to person. You do not search for a COS topic on Google. If you just do a random search on Google is it unlikely that you are looking for a COS topic. So from that perspective, the human-readable URL is not important and does not need to be developed.
- From a SEO point of view, URL's are not the most important things.
- What is important, is that when you see a link, you do read it and if it is a random and long sequence of letters / numbers, then you have less trust in that link. Please see illustration:
- If I understand the issue correctly, then it is not important from the SEO point of view to create human-readable URL's. There maybe some hidden aspects of the issue, so let's discuss tomorrow.
Reference: https://moz.com/blog/15-seo-best-practices-for-structuring-urls

Estimated dev time for this issue is 5 days and the priority of this enhancement is rather low for following reason. Our users mainly share the link via social media or email. When with email then the sender is trusted which makes the link trusted as well. If users shares the link via social media, the title + image of the topic are shown.

**Comment by anettlinno** [comment]
Triage 52. Decided not to implement the human readable links as it is not high priority and is expensive development. 
Closing the issue for future discussion.
