### ISSUE TITLE
Hashtag feature description is confusing to the user

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#776]
**Hashtag feature description is confusing to the user.**
User sees the Hashtag feature text in settings, but it is not exact. It sais, 'use this hashtag in social media and the mentions will be shown below the topic' but in reality, if you 'use this Twitter hashtag, the mentions will be shown below the topic'. In other words, the description of hashtag feature could be worded better to include the fact that it only involves Twitter hashtags and not other social media.
![Screenshot 2021-09-14 at 12 09 14](https://user-images.githubusercontent.com/34899902/133230650-5cc87796-9afc-4e93-a60d-fff9686cd64b.png)

**Comment by loorm** [comment]
Either that, or we can check FB again. We excluded FB, because they did not give out their hashtag firehose for free. Maybe things have changed and we can include FB, too.

**Comment by liinaguiter** [comment]
Yes, good idea to check FB. 
But the term "social media" includes more than just Twitter and FB. We should be clear in our communication. So if it is only Twitter, say "Twitter hashtag" If it is Twitter + FB, then say "Twitter and FB hashtag", etc.

**Comment by anettlinno** [comment]
Triage 56. Issue is understandable and we should be clear in our communications. As time has passed since the last investigation regarding social media hashtags, then we decided to investigate it again and see if we could add any more mediums. If not, we will change the wording as @liinaguiter suggested. 
Approx. investigation time 2h. Sending to investigation.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/69
