### ISSUE TITLE
Help Center

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#815]
**Create a Help Center**
If user needs help with using the Citizen OS platform, they have a place to find answers to their questions, contact us or give us feedback. 

**What is the requested feature?**
When user clicks on the hovering help bubble, the help center opens.

**Additional information.**
The help center and all texts lives on the website (@argoroots develops) and widget is on the platform (@ilmartyrk develops).

**Web version design:** https://www.figma.com/file/eHBSunqUv10fMcWmiEEXiv/Website?node-id=117%3A1463
**Platform version design:** https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=586%3A21598

Website version should be ready by Oct. 31st. 
Widget development Nov 1 - 12.
See full timeline here: https://docs.google.com/spreadsheets/d/1Re9yQg-mgnS4uj5zuJKST_OkSG-m1M2Su-N7ksdfyx4/edit#gid=0

- Help Center is a user manual.
- Search function to work with different wordings - how to join a group, joining a group, group joining.
- No final help texts are ready yet, Argo please use the lengths in the designs. Liina will inserts texts and screenshots. 
- Texts will be in English first, then Estonian, Indonesian and maybe other languages. 
- Translation: paths are translated, but URL is not translated - should be hidden in CrowdIn. Please set up the backend so that it would be possible to translate the Help Center in app language if there´s a need for that.
- At first will produce texts + screenshots. Then will make videos. Help videos will live on youtube (videos will be added later).
- Was this helpful - no need to send every email separately - collect this info somewhere. If can connect with our Plausible account, would be amazing. 

Full discussion on how we reached this point is here: https://github.com/citizenos/citizenos-fe/issues/706

**Comment by liinaguiter** [comment]
@argoroots, regarding the question whether one answer is under more than topic and how many topics are in total, @BeccaMelhuish will write as well, but here is the draft document with the Help Center structure and texts, if that helps. https://docs.google.com/document/d/1MTeva5Sm_TnQdJrd6kajlxau0spfb8Z0/edit

**Comment by BeccaMelhuish** [comment]
Hi @argoroots, replies to you questions below! 

- _Is one question / answer under more than one topic?_
I'm not sure I've fully understood this question, could you clarify a bit? But if you mean whether any 'Level 2' topics might appear with exactly the same content within more than one 'Level 1' section, then yes that may be the case - would be good to allow for that. For example, _Troubleshooting “no permission to access”_ appears in several sections, and will have the same text each time. 

- _How many texts will there be in total? Can you estimate?_
 The [platform Figma design](https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=586%3A21598) has all the topics that are currently planned within it, so you can see the full planned structure there. It's currently 38 topics in total. Though this may of course change a bit/develop over time. I'd say most likely around 40, but could go up to 50.  

Hope this helps, any further questions let me know :)

**Comment by BeccaMelhuish** [comment]
@argoroots and @ilmartyrk I'll move the conversation about the Help icon buttons content ("Level 3") of the website here so you can discuss with each other the technicalities, and then let me and @kevincrepin know if there is any need/what the need is for any further design :) 

So the situation is:

- On the platform version of the Help Centre, we now have a "Level 3" which is where the content relating to certain help buttons (image below) to be added to the platform will sit. [This is what it looks like](https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1480%3A29878) in the platform. 
- Some of the help icon buttons may direct to "Level 2" content (so that's already covered in the previous version of the design), but most will direct to context-specific content which will only ever be viewed when someone clicks on a help icon button ("Level 3").
- For this reason, the "Level 3" content will actually only ever be accessed when someone is using the Help Centre panel on the platform, never when the are using the website version of the Help Centre. It won't be possible to navigate to the "Level 3" content through any other means than clicking on a help icon button (e.g. you can't find it in any of the Help Centre menus/search function), and it shouldn't be possible to find it through a Google search either.   

So the question is, how should this work, technically? As the platform feeds through from the website content, should the Level 3 content be hosted on the website like the rest, but just "hidden" (e.g. at an URL that is not linked to from anywhere else), or @ilmartyrk is there some other preferable solution? And if it does sit on the website, @argoroots do you need a design from us for this, or will just re-use one of the "Level 2" templates for this purpose, seeing as no user should ever land on these pages anyway? 

Example help icon button here so you know what I'm talking about:

![image](https://user-images.githubusercontent.com/61320526/138711560-4c4bc2fe-33a2-416b-bdfd-01fb846df275.png)

Hope that's all clear, but let me know if any questions :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @argoroots @liinaguiter I was thinking about these level 3 help pages. If I understand correctly, these level 3 help pages would mostly have similar content as in the example of attachments. Meaning that they'll probably have some information about limits of input etc. This kind of content could easily change and this can easily end up being out of sync. As limits altered in our API/FE are not linked to info in web help page. My personal preference would be to keep this kind of help info inside our FE project and out of help-center web page structure. I see that from the visual and consistency perspectives it would be great to include them as separate level 3 pages. But I believe it would be faster and more logical to display this info inside FE  popup, hint-bubble or similar kind of solution instead of redirecting user away.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @liinaguiter @argoroots @kevincrepin on a different note. I was trying to implement the solution on our app and run into navigation issue. Modern browsers don't allow navigating inside iframe. There are workarounds, but we would have to decide on how to solve this issue. 

1) We keep it simple, I'll add the help-center panel into our app. In the header it will have home button that basically loads the starting page and the title is always fixed. 
2) This header and navigation part is added from web side and I'll add the closing X and position it to visually look as it should
3) We implement a little more complex using postMessage where our app and web pages iframe can send info about current location and title.

**Comment by anettlinno** [comment]
Triage 50. Bringing Context Sensitive help button issue back to #817 because if we are going to implement the tooltip solution what @ilmartyrk proposed, then Argo does not need to make separate developments in web. 

Moving this back to In prep as we need the list where the Guidance icons are located on the platform from @BeccaMelhuish. We also encourage to discuss over the tooltip solution.

**Comment by anettlinno** [comment]
Triage 50. Regarding the navigation issue @ilmartyrk and @argoroots will discuss this separately (options 1 and 2 from what Ilmar proposed).

**Comment by BeccaMelhuish** [comment]
Hi @ilmartyrk I just had a look through the Help Centre on the platform again to see how it's looking for next week's launch, and there a few things needing adjustment:

**Back button:**
I see the back button still goes to Home, rather than to Level 1 (when on Level 2), was it not possible to resolve this? It's quite an important part of the UX I think.. Also would it be possible to add a "hand symbol" hover state for the back button? Same for the X to close. 

**Header**
Am I right in understanding that it's not possible to have the heading title change, depending on the section the user is in? As this is also quite important for the UX I feel, so we might want to reconsider the design a little if this is the case.  Also I think it's agreed we should change it to "Help Cent**re**" (British English). 
![image](https://user-images.githubusercontent.com/61320526/146528113-0b415406-9f10-44a0-9d9a-d469c59d0b93.png)

**Line spacing and proportions:**
Is line spacing something you are able to adjust yourself, or this needs to be done by Argo? Currently the text which is just standard body text has very big gaps (a bit too big in my opinion) between the lines, but the text that is in bullet points or numbered bullets has very little space (too little) between the lines or between the bullets. This makes it look a bit odd, and also makes the bullet points/numbered bullets harder to read. Same with sizing, if it would be possible to make the lining spacing and proportions closer to the design that Kevin made it would look much slicker. 

I've put screenshots of the design versus the test version so you can see what I mean - the text and headings on the test one are much bigger than on the design, and the bullet point links on the design have nice spaces between them so they are easy to read and look much slicker too. They're just minor things but to my eye they make a lot of difference to how it comes across :) 

![image](https://user-images.githubusercontent.com/61320526/146526642-34479a7b-7d98-4645-9a9e-64e7579e8427.png)
 
**White box at bottom**
Is it possible to get rid of the white box that blocks the bottom of the panel? 
![image](https://user-images.githubusercontent.com/61320526/146527255-219d3881-3c03-484d-a8f6-fb8614546d5d.png)

**Grey box at bottom:**

Here I think it would be good to stick to the design if possible, as then everything is aligned. It's not looking so slick like this: 

![image](https://user-images.githubusercontent.com/61320526/146529217-c51f086e-d870-45f1-a279-aceafc868bd5.png)

**Comment by BeccaMelhuish** [comment]
Also, I sometimes get this message when I click on the Help bubble - is this just a test environment issue, or may happen in the live one too? 

![image](https://user-images.githubusercontent.com/61320526/146528864-4b81716c-2c76-4622-91d8-7fbab21071a8.png)

**Comment by liinaguiter** [comment]
Hi, @BeccaMelhuish, @ilmartyrk. 

Thank you, @BeccaMelhuish, for reviewing!

- The back button goes to home because Argo did not develop level 1 and level 2 separately. They are all one level. If this is very important, then he has to rename the relevant documents in code. Not that big of a job, but something to do. URL translations maybe affected as well. 
- Other questions I do not know how to answer.

**Comment by BeccaMelhuish** [comment]
Hi @liinaguiter OK thanks for explaining! 

The ideal UX would be that the back button takes the user back to the page they were most recently on (i.e. what people are used to on a browser) - so if they came from Home to Level 2 then it would take them back to Home, but if they came from Level 1 to Level 2 then it would take them back to Level 1. Would the fix you mentioned above (renaming the relevant documents in code) mean that this could happen, or would it mean that whenever a user was on Level 2 then "back" would take them to the relevant Level 1, even if they hadn't just come from there?

**Comment by ilmartyrk** [comment]
Hi @BeccaMelhuish  @liinaguiter  currently all content comes from our WEB project, the header title, close x and back arrow are hardcoded to the app side but, all I can currently display is hard-coded as previously said. @liinaguiter will you discuss the issues found by @BeccaMelhuish directly with Argo or should I add my input also? Currently seems that these should all be solved on the web side of project, but I can add any updates if needed by Argo

**Comment by BeccaMelhuish** [comment]
Also @liinaguiter - re the back button issue, I'm thinking that if it will be some time before it's solved (so that it functions just like a browser back button) then as an intermediary quick fix we could just change it to say 'Home' for now, As that's currently how it functions, so would be less confusing/unexpected for the user. Then switch it back to an arrow once the problem is solved.

**Comment by ilmartyrk** [comment]
So as discussion got little lost into Slack I add here that. I have implemented updates related to some issues.

1) We have darkened background when help-center panel is open
2) We display help-center with tooltip on first page visit.  As in 
https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?page-id=586%3A21104&node-id=2323%3A40240&viewport=241%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=2323%3A38847&show-proto-sidebar=1
and
https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?page-id=586%3A21104&nod[…]n-zoom&starting-point-node-id=586%3A22466&show-proto-sidebar=1
3) Also added an animation to help-bubble if tooltip is closed, it is seen by closing help-center panel and after that tooltip 
3) Fixed the navigation menu, now it also opens help-center instead of help topics

Everything is still in our testing environment, I suggest using incognito mode as it stores cookie to only display the view once https://test.app.citizenos.com/en/

**Comment by liinaguiter** [comment]
Updates: 

- @BeccaMelhuish raised the issue that the Help Centre search does not include different words for functions. For example, when searching for the word 'invitations', nothing comes up yet there is help on the topic of how to invite, just not that word specifically (invitations). I've agreed with Argo, that he will not do any work from now on unless you ask him to, @anettlinno (to keep spending in control). This is up to you Anett, to decide when and if to fix this search issue.
- The next steps was to write more texts and create screenshots and Becca has offered to determine for which texts we need to make videos.
- @seppviljar what is the status with translations?
- In the [plan](https://docs.google.com/spreadsheets/d/1Re9yQg-mgnS4uj5zuJKST_OkSG-m1M2Su-N7ksdfyx4/edit#gid=0) we also had User testing of the text / content of the help center.
- I will schedule the newsletter announcing the help centre for Monday and also post social media graphics on Monday.
That's where my work ends.

- @ilmartyrk, I am still directed to the help topic, when I click on 'Help' in the platform menu.

**Comment by seppviljar** [comment]
Translations:
- in-app strings going to translation this week ("For your info" banner)
- content translation into Estonian on hold, we plan to get help from machine translation due to the volume we have
--  @loorm could you finish DeepL registration flow (details in Slack) - it's "must-have" before I  can access their API

**Comment by ilmartyrk** [comment]
@liinaguiter @BeccaMelhuish I have added the tooltip into test and also help link from navigation menu is fixed there. Please confirm if it looks OK and I can send it live. The solution works that I can push it live, but it wont get displayed until it's turned on from configuration. That will give us more time, if we are waiting for translations. Anyway I just need the confirmation that the current solution is OK

**Comment by ilmartyrk** [comment]
From todays meeting I am adding new items to do
- [x] Only display tooltip both on mobile and desktop views
- [x] Check and updated the cookie expiration time to 6 months

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @argoroots A couple of questions re the Help Centre:

- When someone clicks on Yes / No for the "Was this helpful?" question, where does this data go? 
- And when they submit a message to say why it was not helpful (via the pop up that appears if they click "No"), where does this message go? 
- Same for when they submit a Help Request (this goes to the Help email I assume, which @anettlinno has access to?)
- And also for "Give us feedback", where does this feedback go once submitted? 

![image](https://user-images.githubusercontent.com/61320526/168628503-19ac65e8-3286-4535-bd5c-65f55d9a63b9.png)

**Comment by BeccaMelhuish** [comment]
Update: re my previous comment, have now received this info via @anettlinno. (That all the messages are being received to the Help email address, and the Yes/No "Was this helpful?" should be going to Plausible). Though @ilmartyrk we didn't see the Yes/No Plausible data when we looked, does this mean it hasn't been set up, or that we were looking in the wrong place? Tagging @ssin1901 for her info as it's data related. 

However, @anettlinno and I also discussed some UX related issues that need resolving, some of which, from reading through the above thread, I see Argo has already said are fixable - he just needs the go ahead.

**Navigation**
- As discussed above, on the platform version of the Help Centre the back button goes back to "Help Centre home" rather than what was previously viewed by the user. Earlier in the thread, Liina said: _"The back button goes to home because Argo did not develop level 1 and level 2 separately. They are all one level. If this is very important, then he has to rename the relevant documents in code. Not that big of a job, but something to do. URL translations maybe affected as well."_ 
So @anettlinno, shall we give Argo the go ahead to fix this?  

- On the website, the issue is that there is no "back" button or "Help Centre home" button. So once you have navigated to a help topic, the only way to go backwards to the previous layer is the browser back button. And the Citizen OS logo (which would obviously usually be a "home" button) takes you to the Citizen OS home rather than the Help Centre home. I remember that @kevincrepin did add a "back button" to the design, here is a screenshot and [link to the Figma](https://www.figma.com/file/eHBSunqUv10fMcWmiEEXiv/Website?node-id=117%3A1463). This should be added to all pages except the Home Page. 

![image](https://user-images.githubusercontent.com/61320526/169788752-dd6b2f68-cfab-4ed6-9580-ce5e78fcd5ce.png)

**Disappearing Yes/No field**  
After responding to the "Was this helpful? Yes/No" field, that section vanishes! My thoughts are that the flow should be that after submitting either Yes or No, there is confirmation that the responses was submitted, and then the box remains in the same place but with the Yes or No (whichever they chose) in a different shade. (We may also want to think through how it works if they want to change their mind and switch it to the other option - yes or no).
 @anettlinno shall we ask Kevin to design this flow and then ask Argo to develop it?  

And something which Anett and I didn't discuss but which I remember (and see above) was discussed previously, was:

**Search bar problems**
The problem (which Liina previously discussed with Argo) was that the way the search bar works is that if the word appears in the heading or the text then it shows up in the search results. But if the word is not typed exactly the same way as it is in the text, it doesn't appear. So for example, "invitation" brings up zero results, as I only use the shortened word "invites" in the texts. I assume one way to fix this would be the have hidden keywords (in the code but not visible to the user) that we add ourselves, so that they would be pulled up in search results. But just a guess, would need Argo to confirm how this could work.  

![image](https://user-images.githubusercontent.com/61320526/169791826-84089ff9-0953-4b71-9aba-e6d79304b701.png)

The other problem is that for me (and I assume for others too - could someone confirm?) when I click in the search bar, it flashes up with suggestions from previous searches, but they are not all relevant to this site - they are searches I have made in other places (on Google for example, re the baby gifts):

![image](https://user-images.githubusercontent.com/61320526/169792516-67f64666-b90f-4ee6-9145-d0bf3a1c92e5.png)

And when I start typing, it does the same, for example when I type "P":

![image](https://user-images.githubusercontent.com/61320526/169791941-32a01420-f9aa-48a1-acc4-a4e3e5f8b6a1.png)

Earlier in the thread, after discussing these search issues with Argo, Liina said: 
_"I've agreed with Argo, that he will not do any work from now on unless you ask him to, @anettlinno (to keep spending in control). This is up to you Anett, to decide when and if to fix this search issue."_
So @anettlinno what do you think, do we go ahead and ask Argo to fix these? Search is a very important element to get right I think.. 

Tagging @oksks too, just for info as it's website related :)
