### ISSUE TITLE
Context sensitive Help buttons

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#817]
In the https://github.com/citizenos/citizenos-fe/issues/706 discussion, we agreed that we will develop context sensitive help icons, so that in the places where users mostly get stuck whilst using the platform, they can click on the question mark and be directed to the help center to that page. Can be developed once the help center is live and the specific help texts exist. 

I am talking about the question mark icon that will be used in places that create frequent problems. 
![Screenshot 2021-09-16 at 00 34 08](https://user-images.githubusercontent.com/34899902/133512956-18e73ac4-3a8d-4123-a8fb-0b4cd27dcffd.png)

**Comment by anettlinno** [comment]
@kevincrepin, we would appreciate question mark icon design (I think we don´t have it yet?)

@BeccaMelhuish, do we have the information about where on the platform these Guidance icons are located and where in the Help Center users are going to be directed after they click on the Guidance question mark? :)

**Comment by kevincrepin** [comment]
The icon  asset can be found here: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=85%3A71

**Comment by BeccaMelhuish** [comment]
@anettlinno it's a very good point, actually we got a bit side tracked from the original plan, and don't yet have the design for the help buttons in the Figma design! 

In some cases the help button will simply direct the user straight to the relevant Level 2 help topic, but in other cases it will be necessary to have a text that is different, so that it makes sense in the context of what the user is doing at the time. 

So I've started making a design for this in Figma, using as an example adding a help button next to the "ATTACHMENTS" heading in the topic to tell users what the attachment file limits are.

@kevincrepin what do you think of this design? [Here is the link directly to the frame](https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform?node-id=1480%3A29878).

Some things to note in the screenshot below:

- yellow highlight - I'm suggesting help buttons which are not already Level 2 topics have the heading "Help Centre" at the top. So within the structure of the centre, they don't sit within any particular section. 
- red circle - the "back" button, would take the user to the Help Centre Start page. (Which wouldn't really be "back" for them, as they didn't come from there, but more like a "home" button in this situation - hopefully shouldn't be confusing?) 
- red wiggly line - for most of the help buttons there will be a related topic, so in this example, if after reading the help button guidance the users wants step by step instructions on how to add attachments, they can click to find this).
- red arrow - I wanted to add "Help Centre Start Page" at the top of the list of links at the bottom, but still not being fully used to Figma had trouble with this. @kevincrepin it wouldn't let me drag it into the relevant place in the layers list for some reason, might you be able to fix this? 
- I removed the photo for this example, as it wouldn't make sense to have one here, but other help button texts may include photos.

And a few further things to consider:
- @ilmartyrk - something we need to consider is the connection between the website and the platform Help panel. As these help button texts will only be relevant to the platform Help panel, but will presumably need to be included but hidden (e.g. inaccessible except via a direct URL that only we know, or something?) on the website version, as the texts need to feed through from there? (In other words, while there is a chance that people will use the website version of the Help Centre after having searched for help via Google, they won't need to access the Help button texts at all while on the website. As the help buttons are only relevant to users when they are viewing them in the platform, and they are not possible to navigate to in the Help Centre structure, only accessible when clicking on the relevant help button.) What do you think about this? 
- Shall we refer to this level of the Help Centre as "Level 3"? I have currently just put it to the side in the design, but @kevincrepin you can move it to wherever you think it best for it to sit in relation to the other artboards. 
- @liinaguiter this will mean there's one more task to add to Argo's list for the development. But as you can see it is very similar to the existing designs, so hopefully shouldn't add much. Once @kevincrepin has confirmed this one I can make the website version, and then update the Help Centre Github thread so he knows. 
- @anettlinno re where on the platform these buttons are located, I've started making a list in the Help Centre structure google doc but this is currently "work in progress", Will let you know once I have finished it, and then we can see if everyone agrees with where I am suggesting we add them, and whether any important places are missing. 

![image](https://user-images.githubusercontent.com/61320526/138443445-21f280c4-0ad7-4140-aa67-7f34bc4d87ea.png)

**Comment by kevincrepin** [comment]
@BeccaMelhuish fixed it and moved it to the right of LVL 2 frames :)

**Comment by liinaguiter** [comment]
Thank you, @BeccaMelhuish Re: updating Help Centre Github thread so Argo knows.

**Comment by BeccaMelhuish** [comment]
Thanks @kevincrepin! And @liinaguiter and @ilmartyrk - I've moved the conversation to the Help Centre thread now so that Ilmar and Argo can discuss and decide on the technicalities, then I will adjust the website design accordingly :)

**Comment by anettlinno** [comment]
Triage 50. We are going to implement the tooltip solution what @ilmartyrk proposed, then Argo does not need to make separate developments in web.

Moving this back to In prep as we need the list where the Guidance icons are located on the platform from @BeccaMelhuish. We also encourage to discuss over the tooltip solution.

#817

**Comment by anettlinno** [comment]
Friendly reminder to @BeccaMelhuish that we are waiting for your input here :)

**Comment by anettlinno** [comment]
As the platform is going through the UX/UI redesign I will close this issue now and we can come back to Context sensitive Help buttons after redesigned platform is launched (IF needed). Hopefully there is no need for the Help buttons there, but I will tag you just to keep it in mind that we have this conversation here, @kevincrepin :)
