### ISSUE TITLE
Update my account view to include user connection info

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#931]
We have added possibility for new users to connect their account with personal ID after initial log-in. If the user has registered account using e-mail. I believe we need this option under my account too. Possibly also including google and facebook connections there too. I would allow users to delete their Google/Facebook connections, but not allow deleting personal ID connection. This issue is also related to as there is possibility to add user connection, but no place for user to see them https://github.com/citizenos/citizenos-fe/issues/940

**Comment by anettlinno** [comment]
Triage 60. This issue is connected with issues [#235](https://github.com/citizenos/citizenos-api/issues/235) and [#237](https://github.com/citizenos/citizenos-api/issues/237). Sending it back to In Prep to write user stories for all different log-in variations and discuss the security issues, legal issues and other issues that might rise when updating, merging or switching between different accounts.

**Comment by ilmartyrk** [comment]
Moved to https://github.com/citizenos/citizenos-fe/issues/43
