### ISSUE TITLE
BUG: Link does not expire after regenerating link

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#992]
**What is the problem?**
I invited User to the topic and after that regenerated link (for testing purposes, not for fooling people :)). When User clicked on the invitation in email, she got still access to the topic, even though the link was regenerated. 

**Why is this a problem?**
Regenerated link (and email invitations) should expire as agreed (and delivered) in issue #191. 

**Possible solution.**
N/A

**Comment by anettlinno** [comment]
Triage 64. Successfully replicated. Fixing the bug in 30 minutes. 
Sending to TO DO.

**Comment by ilmartyrk** [comment]
Fixed by deleting old invites before creating new. Noticed some things that should be fixed. 
1) Invites should have expire timestamp field, currently they are calculated from "createdAt" field and defined expiration time.  This means that there is no flexibility in expiring individual invites without manipulating "createdAt" field
2) When user clicks on topic invite link that is expired, I would actually check if there is any valid invites for that user as we know that he/she actually has pending invite. If there is pending invite I would use the data from that invite and not display any errors.

@anettlinno  What do you think about these suggestions, should I create a new issue for them?

**Comment by anettlinno** [comment]
> Fixed by deleting old invites before creating new. Noticed some things that should be fixed.
> 
> 1. Invites should have expire timestamp field, currently they are calculated from "createdAt" field and defined expiration time.  This means that there is no flexibility in expiring individual invites without manipulating "createdAt" field
> 2. When user clicks on topic invite link that is expired, I would actually check if there is any valid invites for that user as we know that he/she actually has pending invite. If there is pending invite I would use the data from that invite and not display any errors.
> 
> @anettlinno What do you think about these suggestions, should I create a new issue for them?

@ilmartyrk yes -- good idea! This would make the User experience much better as the expired link information and the newly generated link information is not important for User -- she only wants to access the topic :) So, please create new issue for that. Thanks a lot!
